import { useParams, useNavigate } from "react-router-dom";
import ReportTemplateLayout from "../../components/reportTemplates/ReportTemplateLayout";

// Switzerland — same thin wrapper as every other jurisdiction. Lohnausweis
// certificates and ELM envelopes are generated by the Swiss reporting
// endpoints (Step 14); this page manages the shared report-template lifecycle.
export default function CHReportTemplatesPage() {
  const { jurisdiction } = useParams();
  const navigate = useNavigate();
  return (
    <ReportTemplateLayout
      country="CH" countryName="Switzerland"
      initialState={jurisdiction ? decodeURIComponent(jurisdiction) : ""}
      onStateChange={(state) =>
        navigate(state ? `/super-admin/report-templates/switzerland/${encodeURIComponent(state)}` : "/super-admin/report-templates/switzerland")
      }
    />
  );
}
