"""scripts/hk_generate_registers.py — generate the HK configuration registers FROM a freshly seeded scratch
database (never hand-written): lineage, consumer, version, report-template
version and source-evidence registers. Run with PAYROLL_DATABASE_URL pointing
at a scratch SQLite file:

  PAYROLL_DATABASE_URL=sqlite:///scratch.db python scripts/hk_generate_registers.py

It builds its own in-memory database and writes nothing to any configured one."""
import os
import sys
from collections import defaultdict
from datetime import date

assert "sqlite" in os.environ.get("PAYROLL_DATABASE_URL", ""), "scratch SQLite only"
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "backend"))
os.chdir(os.path.join(ROOT, "backend"))

from sqlalchemy import create_engine  # noqa: E402
from sqlalchemy.orm import sessionmaker  # noqa: E402
from sqlalchemy.pool import StaticPool  # noqa: E402

import app.main  # noqa: E402,F401  (registers every model)
from app.database import Base  # noqa: E402

engine = create_engine("sqlite://", connect_args={"check_same_thread": False}, poolclass=StaticPool)
Base.metadata.create_all(engine)
db = sessionmaker(bind=engine)()

from scripts.seed_hong_kong_canonical_pack import seed_hong_kong_all  # noqa: E402
from scripts.seed_statutory_report_templates import seed_hong_kong  # noqa: E402
from app.modules.payroll import hong_kong_service# noqa: E402
from app.modules.payroll.models import ReportTemplate, SourceArtifact  # noqa: E402

packs = seed_hong_kong_all(db)
seed_hong_kong(db)
db.commit()
OUT = os.path.join(ROOT, "docs", "HONG_KONG_RELEASE_EVIDENCE")
GEN = (f"> Generated by `scripts/hk_generate_registers.py` from a freshly seeded scratch database on {date.today().isoformat()} "
       "(the canonical seed + template seed, exactly as a production seed would create them). Never hand-edited: "
       "regenerate after any seed change.\n")
esc = lambda v: str(v if v not in (None, "") else "—").replace("|", "\\|").replace("\n", " ")  # noqa: E731

# ── lineage + consumer registers ──
lineage = ["# HK CONFIGURATION LINEAGE REGISTER\n", GEN,
           "Every governed HK statutory value: value → unit → effective window → official source (agency, title, URL, "
           "SHA-256, review state) → status → consuming engine module. `SOURCE_HASH_REQUIRED` means no official "
           "artifact hash could be stored — never an invented hash. `UNVERIFIED — G1` means the value awaits the HK "
           "statutory specialist (gate G1).\n"]
consumers = defaultdict(lambda: {"keys": set(), "packs": set(), "rows": 0})
status_count = defaultdict(int)
for pack in packs:
    out = hong_kong_service.domains(db, pack.id)
    lineage.append(f"\n## {pack.pack_id} v{pack.version} — YA {pack.tax_year} ({out['pack']['effectiveFrom']} → "
                   f"{out['pack']['effectiveTo']}), seeded status {pack.status}, {out['total']} values, "
                   f"unmapped {len(out['unmapped'])}\n")
    for d in out["domains"]:
        lineage.append(f"\n### {d['label']} — {d['count']} values (consumer `{d['consumer']}`)\n")
        if d.get("notice"):
            lineage.append(f"\n> {d['notice']}\n")
        lineage.append("\n| Key | Item | Value | Unit | Effective | Source | SHA-256 | Status |\n|---|---|---|---|---|---|---|---|\n")
        for r in d["rows"]:
            src = r["source"] or {}
            sha = (src.get("sha256") or "SOURCE_HASH_REQUIRED")
            lineage.append(f"| {esc(r['key'])} | {esc(r['label'])} | {esc(r['value'])} | {esc(r['unit'])} | "
                           f"{esc(r['effectiveFrom'])} → {esc(r['effectiveTo'])} | {esc(src.get('agency'))}: "
                           f"{esc(src.get('title'))} | `{sha[:16]}{'…' if len(sha) > 16 else ''}` | {esc(r['status'])} |\n")
            status_count[r["status"]] += 1
            c = consumers[(d["label"], r["consumer"])]
            c["keys"].add(r["key"]); c["packs"].add(pack.pack_id); c["rows"] += 1
lineage.append("\n## Totals\n\n" + "\n".join(f"- {k}: {v}" for k, v in sorted(status_count.items())) + "\n")
open(os.path.join(OUT, "HK_CONFIGURATION_LINEAGE_REGISTER.md"), "w", encoding="utf8").write("".join(lineage))

cons = ["# HK CONFIGURATION CONSUMER REGISTER\n", GEN,
        "Which engine module consumes each configuration domain. Every consumer path is verified to exist by "
        "`test_every_hk_configuration_row_is_governed_documented_sourced_consumed_and_exposed`.\n\n"
        "| Domain | Consumer | Rows | Packs | Keys |\n|---|---|---|---|---|\n"]
for (label, consumer), c in sorted(consumers.items()):
    cons.append(f"| {esc(label)} | `{esc(consumer)}` | {c['rows']} | {', '.join(sorted(c['packs']))} | "
                f"{esc(', '.join(sorted(c['keys'])))} |\n")
open(os.path.join(OUT, "HK_CONFIGURATION_CONSUMER_REGISTER.md"), "w", encoding="utf8").write("".join(cons))

# ── version register ──
ver = ["# HK CONFIGURATION VERSION REGISTER\n", GEN,
       "Version states are derived (never stored): CURRENT_ACTIVE / NEXT_PUBLISHED (Active, starts later) / "
       "PAST_ACTIVE / DRAFT / FUTURE_DRAFT / SUPERSEDED / RETIRED. An Active version is never edited in place — "
       "a change or a rollback is a new Draft version (Statutory Configuration → Create new version). The seed creates "
       "every version as Draft; activation is gated (G1 + pack-bound golden + four-eyes). Production has no HK "
       "pack at all: the HK migration has never been applied there.\n\n"
       "| Pack | Version | YA | Effective | Seeded status | State today | Approved by |\n|---|---|---|---|---|---|---|\n"]
for v in hong_kong_service.versions(db, date.today()):
    ver.append(f"| {v['packId']} | {v['version']} | {v['yearOfAssessment']} | {v['effectiveFrom']} → {v['effectiveTo']} | "
               f"{v['status']} | {v['versionState']} | {esc(v['approvedById'])} |\n")
ver.append("\n## Year-on-year differences (2025 → 2026)\n\n")
diff = hong_kong_service.compare(db, packs[0].id, packs[1].id)
ver.append(f"{len(diff['changed'])} changed · {len(diff['added'])} added · {len(diff['removed'])} removed · "
           f"{diff['unchanged']} unchanged.\n\n| Domain | Item | Field | 2025/26 | 2026/27 |\n|---|---|---|---|---|\n")
for c in diff["changed"]:
    for field, v in c["changes"].items():
        ver.append(f"| {esc(c['domain'])} | {esc(c['label'])} | {field} | {esc(v['from'])} | {esc(v['to'])} |\n")
for r in diff["added"]:
    ver.append(f"| {esc(r['domain'])} | {esc(r['label'])} | added | — | {esc(r['value'])} |\n")
for r in diff["removed"]:
    ver.append(f"| {esc(r['domain'])} | {esc(r['label'])} | removed | {esc(r['value'])} | — |\n")
open(os.path.join(OUT, "HK_CONFIGURATION_VERSION_REGISTER.md"), "w", encoding="utf8").write("".join(ver))

# ── report template version register ──
tpl = ["# HK REPORT TEMPLATE VERSION REGISTER\n", GEN,
       "Template lifecycle Draft → Review → Approved → Published → Active → Superseded (shared). HK templates may go "
       "Active only with reviewed source evidence and an activator other than the approver; generation needs an "
       "Active template for the EXACT year key (no fallback). Content hash = SHA-256 of the field structure "
       "(computed, never stored).\n\n"
       "| Template | Report type | Year key | Version | Status | Source document | Content hash |\n|---|---|---|---|---|---|---|\n"]
for t in db.query(ReportTemplate).filter(ReportTemplate.jurisdiction_country == "HK").order_by(
        ReportTemplate.report_type, ReportTemplate.reporting_year, ReportTemplate.version):
    tpl.append(f"| {esc(t.template_key)} | {t.report_type} | {t.reporting_year} | {t.version} | {t.status} | "
               f"{esc(t.source_document_id)} | `{hong_kong_service.template_content_hash(db, t)[:16]}…` |\n")
tpl.append("\n## Coverage (current and next period)\n\n| Report type | Year key | Period | Active template |\n|---|---|---|---|\n")
for cov in hong_kong_service.template_coverage(db):
    tpl.append(f"| {cov['reportType']} | {cov['yearKey']} | {cov['period']} | {esc(cov['active'])} |\n")
open(os.path.join(OUT, "HK_REPORT_TEMPLATE_VERSION_REGISTER.md"), "w", encoding="utf8").write("".join(tpl))

# ── source evidence register ──
used = defaultdict(int)
for pack in packs:
    for d in hong_kong_service.domains(db, pack.id)["domains"]:
        for r in d["rows"]:
            if r["source"]:
                used[r["source"]["id"]] += 1
src = ["# HK SOURCE EVIDENCE REGISTER\n", GEN,
       "Official publications the HK statutory values were taken from. A hash is stored only where the official "
       "document was retrieved and hashed; otherwise SOURCE_HASH_REQUIRED (never invented). `[UNVERIFIED` in a "
       "title marks a value awaiting the G1 specialist. Operator-uploaded evidence (HK-GATE-*, HK-DECISION-*, IRD "
       "approval letters, eMPF certification) is added through Source Evidence and is NOT in a fresh seed.\n\n"
       "| ID | Agency | Title | Form / tag | Published | URL | SHA-256 | File stored | Reviewed | Rows citing |\n"
       "|---|---|---|---|---|---|---|---|---|---|\n"]
for a in db.query(SourceArtifact).order_by(SourceArtifact.id):
    if used.get(a.id) or (a.form_number or "").startswith("HK"):
        src.append(f"| {a.id} | {esc(a.agency)} | {esc(a.title)} | {esc(a.form_number)} | {esc(a.publication_date)} | "
                   f"{esc(a.source_url)} | `{esc(a.checksum_sha256)}` | {'yes' if a.file_path else 'no'} | "
                   f"{'yes' if a.reviewer_id else 'no'} | {used.get(a.id, 0)} |\n")
open(os.path.join(OUT, "HK_SOURCE_EVIDENCE_REGISTER.md"), "w", encoding="utf8").write("".join(src))
print("registers written", dict(status_count), len(consumers))
