"""baseline: existing schema

Revision ID: 0b624a4a7481
Revises: 
Create Date: 2026-08-11 14:45:10.549452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b624a4a7481'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('organization_code', sa.String(length=20), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company_type', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('tax_no', sa.String(length=50), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_organization_code'), 'organizations', ['organization_code'], unique=True)
    op.create_table('payroll_jurisdiction_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pack_id', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction_country', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction_state', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('compliance_owner', sa.String(length=150), nullable=True),
    sa.Column('engineering_owner', sa.String(length=150), nullable=True),
    sa.Column('source_references', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_id', 'version', name='uq_jurisdiction_pack_id_version')
    )
    op.create_index('ix_jurisdiction_packs_country_state', 'payroll_jurisdiction_packs', ['jurisdiction_country', 'jurisdiction_state'], unique=False)
    op.create_index(op.f('ix_payroll_jurisdiction_packs_id'), 'payroll_jurisdiction_packs', ['id'], unique=False)
    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_settings_id'), 'platform_settings', ['id'], unique=False)
    op.create_index(op.f('ix_platform_settings_key'), 'platform_settings', ['key'], unique=True)
    op.create_table('platform_statutory_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jurisdiction_country', sa.String(length=10), server_default='IN', nullable=False),
    sa.Column('component_key', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('employee_share', sa.String(length=50), nullable=False),
    sa.Column('employer_share', sa.String(length=50), nullable=False),
    sa.Column('total', sa.String(length=50), nullable=False),
    sa.Column('employee_rate_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('employer_rate_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('flat_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_country', 'component_key', name='uq_global_rate_country_component')
    )
    op.create_index(op.f('ix_platform_statutory_rates_id'), 'platform_statutory_rates', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ORG_ADMIN', 'PAYROLL_ADMIN', 'EMPLOYEE', name='userrole'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_foreign_key(
        'organizations_created_by_user_id_fkey',
        'organizations', 'users',
        ['created_by_user_id'], ['id'],
        ondelete='SET NULL'
    )
    op.create_table('payroll_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_activity_log_created_at'), 'payroll_activity_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_payroll_activity_log_id'), 'payroll_activity_log', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_activity_log_organization_id'), 'payroll_activity_log', ['organization_id'], unique=False)
    op.create_table('payroll_company_compliance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('tax_no', sa.String(length=50), nullable=True),
    sa.Column('employer_id', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('jurisdiction_country', sa.String(length=100), nullable=True),
    sa.Column('jurisdiction_state', sa.String(length=100), nullable=True),
    sa.Column('compliance_pack', sa.String(length=100), nullable=True),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('settlement_bank', sa.String(length=100), nullable=True),
    sa.Column('settlement_acc', sa.String(length=50), nullable=True),
    sa.Column('active_pack_id', sa.Integer(), nullable=True),
    sa.Column('configured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['active_pack_id'], ['payroll_jurisdiction_packs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_company_compliance_id'), 'payroll_company_compliance', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_company_compliance_organization_id'), 'payroll_company_compliance', ['organization_id'], unique=True)
    op.create_table('payroll_compliance_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_compliance_documents_country'), 'payroll_compliance_documents', ['country'], unique=False)
    op.create_index(op.f('ix_payroll_compliance_documents_id'), 'payroll_compliance_documents', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_compliance_documents_organization_id'), 'payroll_compliance_documents', ['organization_id'], unique=False)
    op.create_table('payroll_contribution_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('component_key', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('employee_share', sa.String(length=50), nullable=False),
    sa.Column('employer_share', sa.String(length=50), nullable=False),
    sa.Column('total', sa.String(length=50), nullable=False),
    sa.Column('employee_rate_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('employer_rate_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('flat_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('jurisdiction_country', sa.String(length=10), server_default='IN', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'jurisdiction_country', 'component_key', name='uq_contribution_rate_org_country_component')
    )
    op.create_index(op.f('ix_payroll_contribution_rates_id'), 'payroll_contribution_rates', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_contribution_rates_organization_id'), 'payroll_contribution_rates', ['organization_id'], unique=False)
    op.create_table('payroll_custom_field_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('select_options', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'field_key', name='uq_payroll_custom_field_org_key')
    )
    op.create_index(op.f('ix_payroll_custom_field_definitions_id'), 'payroll_custom_field_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_custom_field_definitions_organization_id'), 'payroll_custom_field_definitions', ['organization_id'], unique=False)
    op.create_table('payroll_email_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('from_display_name', sa.String(length=150), nullable=True),
    sa.Column('notify_payslip_ready', sa.Boolean(), nullable=False),
    sa.Column('notify_run_approved', sa.Boolean(), nullable=False),
    sa.Column('use_custom_smtp', sa.Boolean(), nullable=False),
    sa.Column('custom_smtp_host', sa.String(length=255), nullable=True),
    sa.Column('custom_smtp_port', sa.String(length=10), nullable=True),
    sa.Column('custom_smtp_username', sa.String(length=255), nullable=True),
    sa.Column('custom_smtp_password', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_email_settings_id'), 'payroll_email_settings', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_email_settings_organization_id'), 'payroll_email_settings', ['organization_id'], unique=True)
    op.create_table('payroll_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('legacy_code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('work_state', sa.String(length=100), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('ctc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('basic', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('hra', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('uan', sa.String(length=20), nullable=True),
    sa.Column('ifsc', sa.String(length=20), nullable=True),
    sa.Column('custom_fields', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'employee_code', name='uq_payroll_employee_org_code')
    )
    op.create_index(op.f('ix_payroll_employees_id'), 'payroll_employees', ['id'], unique=False)
    op.create_index('ix_payroll_employees_org_status', 'payroll_employees', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_payroll_employees_organization_id'), 'payroll_employees', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payroll_employees_status'), 'payroll_employees', ['status'], unique=False)
    op.create_table('payroll_enterprise_jurisdictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('general_config', sa.JSON(), nullable=True),
    sa.Column('compliance_config', sa.JSON(), nullable=True),
    sa.Column('payroll_rules_config', sa.JSON(), nullable=True),
    sa.Column('configured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'country_code', name='uq_org_jurisdiction_country')
    )
    op.create_index('ix_enterprise_jurisdictions_org_status', 'payroll_enterprise_jurisdictions', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_payroll_enterprise_jurisdictions_id'), 'payroll_enterprise_jurisdictions', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_enterprise_jurisdictions_organization_id'), 'payroll_enterprise_jurisdictions', ['organization_id'], unique=False)
    op.create_table('payroll_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'country', 'date', name='uq_payroll_holiday_org_country_date')
    )
    op.create_index(op.f('ix_payroll_holidays_id'), 'payroll_holidays', ['id'], unique=False)
    op.create_index('ix_payroll_holidays_org_date', 'payroll_holidays', ['organization_id', 'date'], unique=False)
    op.create_index(op.f('ix_payroll_holidays_organization_id'), 'payroll_holidays', ['organization_id'], unique=False)
    op.create_table('payroll_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.Date(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('calculation_mode', sa.String(length=20), nullable=False),
    sa.Column('bank_export_format', sa.String(length=10), nullable=False),
    sa.Column('enterprise_status', sa.String(length=20), nullable=False),
    sa.Column('enterprise_activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('configured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'is_default', name='uq_one_default_per_org', sqlite_on_conflict=None)
    )
    op.create_index(op.f('ix_payroll_policies_id'), 'payroll_policies', ['id'], unique=False)
    op.create_index('ix_payroll_policies_org_status', 'payroll_policies', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_payroll_policies_organization_id'), 'payroll_policies', ['organization_id'], unique=False)
    op.create_table('payroll_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_code', sa.String(length=30), nullable=True),
    sa.Column('period_label', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('total_gross', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_deductions', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_taxes', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_employer_contribution', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_net', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authorized_by', sa.Integer(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_by', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calculation_mode', sa.String(length=20), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['authorized_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_code')
    )
    op.create_index(op.f('ix_payroll_runs_id'), 'payroll_runs', ['id'], unique=False)
    op.create_index('ix_payroll_runs_org_period_start', 'payroll_runs', ['organization_id', 'period_start'], unique=False)
    op.create_index('ix_payroll_runs_org_status', 'payroll_runs', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_payroll_runs_organization_id'), 'payroll_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payroll_runs_status'), 'payroll_runs', ['status'], unique=False)
    op.create_table('payroll_tax_slabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rate_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rate_label', sa.String(length=20), nullable=False),
    sa.Column('tax_formula', sa.String(length=150), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('jurisdiction_country', sa.String(length=10), server_default='IN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_tax_slabs_id'), 'payroll_tax_slabs', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_tax_slabs_organization_id'), 'payroll_tax_slabs', ['organization_id'], unique=False)
    op.create_table('payroll_update_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('fields_config', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_update_forms_id'), 'payroll_update_forms', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_update_forms_organization_id'), 'payroll_update_forms', ['organization_id'], unique=False)
    op.create_table('security_action_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.Enum('INVITE', 'RESET', name='securityactionpurpose'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_action_tokens_email'), 'security_action_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_security_action_tokens_id'), 'security_action_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_security_action_tokens_token_hash'), 'security_action_tokens', ['token_hash'], unique=True)
    op.create_table('payroll_leave_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_balances', sa.JSON(), nullable=True),
    sa.Column('period_label', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['payroll_employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'employee_id', name='uq_payroll_leave_org_emp')
    )
    op.create_index(op.f('ix_payroll_leave_allocations_employee_id'), 'payroll_leave_allocations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_leave_allocations_id'), 'payroll_leave_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_leave_allocations_organization_id'), 'payroll_leave_allocations', ['organization_id'], unique=False)
    op.create_index('ix_payroll_leave_org', 'payroll_leave_allocations', ['organization_id'], unique=False)
    op.create_table('payroll_leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_code', sa.String(length=30), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['payroll_employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_code')
    )
    op.create_index('ix_payroll_leave_req_org', 'payroll_leave_requests', ['organization_id'], unique=False)
    op.create_index('ix_payroll_leave_req_status', 'payroll_leave_requests', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_payroll_leave_requests_employee_id'), 'payroll_leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_leave_requests_id'), 'payroll_leave_requests', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_leave_requests_organization_id'), 'payroll_leave_requests', ['organization_id'], unique=False)
    op.create_table('payroll_policy_employee_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.Column('weekly_off', sa.JSON(), nullable=True),
    sa.Column('expected_hours', sa.Integer(), nullable=False),
    sa.Column('minimum_hours', sa.Integer(), nullable=False),
    sa.Column('paid_leave_eligible', sa.Boolean(), nullable=False),
    sa.Column('grace_time_minutes', sa.Integer(), nullable=False),
    sa.Column('half_day_rule', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['payroll_policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'category', name='uq_policy_category')
    )
    op.create_index(op.f('ix_payroll_policy_employee_categories_id'), 'payroll_policy_employee_categories', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_policy_employee_categories_policy_id'), 'payroll_policy_employee_categories', ['policy_id'], unique=False)
    op.create_table('payroll_policy_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('provider_key', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['payroll_policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'category', 'provider_key', name='uq_policy_integration')
    )
    op.create_index(op.f('ix_payroll_policy_integrations_id'), 'payroll_policy_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_policy_integrations_policy_id'), 'payroll_policy_integrations', ['policy_id'], unique=False)
    op.create_table('payroll_policy_leave_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['payroll_policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'rule_type', name='uq_policy_leave_rule_type')
    )
    op.create_index(op.f('ix_payroll_policy_leave_rules_id'), 'payroll_policy_leave_rules', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_policy_leave_rules_policy_id'), 'payroll_policy_leave_rules', ['policy_id'], unique=False)
    op.create_table('payroll_policy_overtime_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('minimum_overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['payroll_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_policy_overtime_rules_id'), 'payroll_policy_overtime_rules', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_policy_overtime_rules_policy_id'), 'payroll_policy_overtime_rules', ['policy_id'], unique=True)
    op.create_table('payroll_update_form_sends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['payroll_employees.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['payroll_update_forms.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_update_form_sends_employee_id'), 'payroll_update_form_sends', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_update_form_sends_form_id'), 'payroll_update_form_sends', ['form_id'], unique=False)
    op.create_index(op.f('ix_payroll_update_form_sends_id'), 'payroll_update_form_sends', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_update_form_sends_organization_id'), 'payroll_update_form_sends', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payroll_update_form_sends_token'), 'payroll_update_form_sends', ['token'], unique=True)
    op.create_table('payslip_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payslip_number', sa.String(length=30), nullable=True),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_name', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('uan', sa.String(length=20), nullable=True),
    sa.Column('ifsc', sa.String(length=20), nullable=True),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('hra', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('special_allowance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('overtime', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('additional_compensation', sa.Numeric(precision=12, scale=2), server_default='0', nullable=True),
    sa.Column('gross_pay', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payable_days', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_working_days', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('unpaid_leave_days', sa.Integer(), server_default='0', nullable=True),
    sa.Column('attendance_deduction', sa.Numeric(precision=12, scale=2), server_default='0', nullable=True),
    sa.Column('per_day_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pf', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('esi', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('professional_tax', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tds', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('social_security', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('medicare', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ni_employee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('employer_pf', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('employer_esi', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('employer_social_security', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('employer_medicare', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('employer_pension', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_pay', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['payroll_employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_run_id', 'employee_id', name='uq_payslip_run_employee'),
    sa.UniqueConstraint('payslip_number')
    )
    op.create_index(op.f('ix_payslip_items_employee_id'), 'payslip_items', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payslip_items_id'), 'payslip_items', ['id'], unique=False)
    op.create_index('ix_payslip_items_org_status', 'payslip_items', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_payslip_items_organization_id'), 'payslip_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payslip_items_payroll_run_id'), 'payslip_items', ['payroll_run_id'], unique=False)
    op.create_index(op.f('ix_payslip_items_status'), 'payslip_items', ['status'], unique=False)
    op.create_table('payroll_attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_code', sa.String(length=30), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.String(length=10), nullable=True),
    sa.Column('check_out', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=True),
    sa.Column('hours', sa.String(length=10), nullable=True),
    sa.Column('rewards', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bonus', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('other_compensation', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('leave_request_id', sa.Integer(), nullable=True),
    sa.Column('is_half_day', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['payroll_employees.id'], ),
    sa.ForeignKeyConstraint(['leave_request_id'], ['payroll_leave_requests.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payroll_attendance_emp_date', 'payroll_attendance_records', ['employee_id', 'date'], unique=False)
    op.create_index('ix_payroll_attendance_org_date', 'payroll_attendance_records', ['organization_id', 'date'], unique=False)
    op.create_index(op.f('ix_payroll_attendance_records_date'), 'payroll_attendance_records', ['date'], unique=False)
    op.create_index(op.f('ix_payroll_attendance_records_employee_id'), 'payroll_attendance_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_attendance_records_id'), 'payroll_attendance_records', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_attendance_records_leave_request_id'), 'payroll_attendance_records', ['leave_request_id'], unique=False)
    op.create_index(op.f('ix_payroll_attendance_records_organization_id'), 'payroll_attendance_records', ['organization_id'], unique=False)
    op.create_table('payroll_inbound_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('message_uid', sa.String(length=100), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('matched_employee_id', sa.Integer(), nullable=True),
    sa.Column('leave_request_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['leave_request_id'], ['payroll_leave_requests.id'], ),
    sa.ForeignKeyConstraint(['matched_employee_id'], ['payroll_employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'message_uid', name='uq_org_message_uid')
    )
    op.create_index('ix_inbound_messages_org_status', 'payroll_inbound_messages', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_payroll_inbound_messages_id'), 'payroll_inbound_messages', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_inbound_messages_organization_id'), 'payroll_inbound_messages', ['organization_id'], unique=False)
    op.create_table('payroll_update_form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('send_id', sa.Integer(), nullable=False),
    sa.Column('submitted_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['send_id'], ['payroll_update_form_sends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_update_form_submissions_id'), 'payroll_update_form_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_update_form_submissions_organization_id'), 'payroll_update_form_submissions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payroll_update_form_submissions_send_id'), 'payroll_update_form_submissions', ['send_id'], unique=False)
    op.create_index(op.f('ix_payroll_update_form_submissions_status'), 'payroll_update_form_submissions', ['status'], unique=False)
    op.create_table('payroll_inbound_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['payroll_inbound_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_inbound_attachments_id'), 'payroll_inbound_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_inbound_attachments_message_id'), 'payroll_inbound_attachments', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_inbound_attachments_message_id'), table_name='payroll_inbound_attachments')
    op.drop_index(op.f('ix_payroll_inbound_attachments_id'), table_name='payroll_inbound_attachments')
    op.drop_table('payroll_inbound_attachments')
    op.drop_index(op.f('ix_payroll_update_form_submissions_status'), table_name='payroll_update_form_submissions')
    op.drop_index(op.f('ix_payroll_update_form_submissions_send_id'), table_name='payroll_update_form_submissions')
    op.drop_index(op.f('ix_payroll_update_form_submissions_organization_id'), table_name='payroll_update_form_submissions')
    op.drop_index(op.f('ix_payroll_update_form_submissions_id'), table_name='payroll_update_form_submissions')
    op.drop_table('payroll_update_form_submissions')
    op.drop_index(op.f('ix_payroll_inbound_messages_organization_id'), table_name='payroll_inbound_messages')
    op.drop_index(op.f('ix_payroll_inbound_messages_id'), table_name='payroll_inbound_messages')
    op.drop_index('ix_inbound_messages_org_status', table_name='payroll_inbound_messages')
    op.drop_table('payroll_inbound_messages')
    op.drop_index(op.f('ix_payroll_attendance_records_organization_id'), table_name='payroll_attendance_records')
    op.drop_index(op.f('ix_payroll_attendance_records_leave_request_id'), table_name='payroll_attendance_records')
    op.drop_index(op.f('ix_payroll_attendance_records_id'), table_name='payroll_attendance_records')
    op.drop_index(op.f('ix_payroll_attendance_records_employee_id'), table_name='payroll_attendance_records')
    op.drop_index(op.f('ix_payroll_attendance_records_date'), table_name='payroll_attendance_records')
    op.drop_index('ix_payroll_attendance_org_date', table_name='payroll_attendance_records')
    op.drop_index('ix_payroll_attendance_emp_date', table_name='payroll_attendance_records')
    op.drop_table('payroll_attendance_records')
    op.drop_index(op.f('ix_payslip_items_status'), table_name='payslip_items')
    op.drop_index(op.f('ix_payslip_items_payroll_run_id'), table_name='payslip_items')
    op.drop_index(op.f('ix_payslip_items_organization_id'), table_name='payslip_items')
    op.drop_index('ix_payslip_items_org_status', table_name='payslip_items')
    op.drop_index(op.f('ix_payslip_items_id'), table_name='payslip_items')
    op.drop_index(op.f('ix_payslip_items_employee_id'), table_name='payslip_items')
    op.drop_table('payslip_items')
    op.drop_index(op.f('ix_payroll_update_form_sends_token'), table_name='payroll_update_form_sends')
    op.drop_index(op.f('ix_payroll_update_form_sends_organization_id'), table_name='payroll_update_form_sends')
    op.drop_index(op.f('ix_payroll_update_form_sends_id'), table_name='payroll_update_form_sends')
    op.drop_index(op.f('ix_payroll_update_form_sends_form_id'), table_name='payroll_update_form_sends')
    op.drop_index(op.f('ix_payroll_update_form_sends_employee_id'), table_name='payroll_update_form_sends')
    op.drop_table('payroll_update_form_sends')
    op.drop_index(op.f('ix_payroll_policy_overtime_rules_policy_id'), table_name='payroll_policy_overtime_rules')
    op.drop_index(op.f('ix_payroll_policy_overtime_rules_id'), table_name='payroll_policy_overtime_rules')
    op.drop_table('payroll_policy_overtime_rules')
    op.drop_index(op.f('ix_payroll_policy_leave_rules_policy_id'), table_name='payroll_policy_leave_rules')
    op.drop_index(op.f('ix_payroll_policy_leave_rules_id'), table_name='payroll_policy_leave_rules')
    op.drop_table('payroll_policy_leave_rules')
    op.drop_index(op.f('ix_payroll_policy_integrations_policy_id'), table_name='payroll_policy_integrations')
    op.drop_index(op.f('ix_payroll_policy_integrations_id'), table_name='payroll_policy_integrations')
    op.drop_table('payroll_policy_integrations')
    op.drop_index(op.f('ix_payroll_policy_employee_categories_policy_id'), table_name='payroll_policy_employee_categories')
    op.drop_index(op.f('ix_payroll_policy_employee_categories_id'), table_name='payroll_policy_employee_categories')
    op.drop_table('payroll_policy_employee_categories')
    op.drop_index(op.f('ix_payroll_leave_requests_organization_id'), table_name='payroll_leave_requests')
    op.drop_index(op.f('ix_payroll_leave_requests_id'), table_name='payroll_leave_requests')
    op.drop_index(op.f('ix_payroll_leave_requests_employee_id'), table_name='payroll_leave_requests')
    op.drop_index('ix_payroll_leave_req_status', table_name='payroll_leave_requests')
    op.drop_index('ix_payroll_leave_req_org', table_name='payroll_leave_requests')
    op.drop_table('payroll_leave_requests')
    op.drop_index('ix_payroll_leave_org', table_name='payroll_leave_allocations')
    op.drop_index(op.f('ix_payroll_leave_allocations_organization_id'), table_name='payroll_leave_allocations')
    op.drop_index(op.f('ix_payroll_leave_allocations_id'), table_name='payroll_leave_allocations')
    op.drop_index(op.f('ix_payroll_leave_allocations_employee_id'), table_name='payroll_leave_allocations')
    op.drop_table('payroll_leave_allocations')
    op.drop_index(op.f('ix_security_action_tokens_token_hash'), table_name='security_action_tokens')
    op.drop_index(op.f('ix_security_action_tokens_id'), table_name='security_action_tokens')
    op.drop_index(op.f('ix_security_action_tokens_email'), table_name='security_action_tokens')
    op.drop_table('security_action_tokens')
    op.drop_index(op.f('ix_payroll_update_forms_organization_id'), table_name='payroll_update_forms')
    op.drop_index(op.f('ix_payroll_update_forms_id'), table_name='payroll_update_forms')
    op.drop_table('payroll_update_forms')
    op.drop_index(op.f('ix_payroll_tax_slabs_organization_id'), table_name='payroll_tax_slabs')
    op.drop_index(op.f('ix_payroll_tax_slabs_id'), table_name='payroll_tax_slabs')
    op.drop_table('payroll_tax_slabs')
    op.drop_index(op.f('ix_payroll_runs_status'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_organization_id'), table_name='payroll_runs')
    op.drop_index('ix_payroll_runs_org_status', table_name='payroll_runs')
    op.drop_index('ix_payroll_runs_org_period_start', table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_id'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    op.drop_index(op.f('ix_payroll_policies_organization_id'), table_name='payroll_policies')
    op.drop_index('ix_payroll_policies_org_status', table_name='payroll_policies')
    op.drop_index(op.f('ix_payroll_policies_id'), table_name='payroll_policies')
    op.drop_table('payroll_policies')
    op.drop_index(op.f('ix_payroll_holidays_organization_id'), table_name='payroll_holidays')
    op.drop_index('ix_payroll_holidays_org_date', table_name='payroll_holidays')
    op.drop_index(op.f('ix_payroll_holidays_id'), table_name='payroll_holidays')
    op.drop_table('payroll_holidays')
    op.drop_index(op.f('ix_payroll_enterprise_jurisdictions_organization_id'), table_name='payroll_enterprise_jurisdictions')
    op.drop_index(op.f('ix_payroll_enterprise_jurisdictions_id'), table_name='payroll_enterprise_jurisdictions')
    op.drop_index('ix_enterprise_jurisdictions_org_status', table_name='payroll_enterprise_jurisdictions')
    op.drop_table('payroll_enterprise_jurisdictions')
    op.drop_index(op.f('ix_payroll_employees_status'), table_name='payroll_employees')
    op.drop_index(op.f('ix_payroll_employees_organization_id'), table_name='payroll_employees')
    op.drop_index('ix_payroll_employees_org_status', table_name='payroll_employees')
    op.drop_index(op.f('ix_payroll_employees_id'), table_name='payroll_employees')
    op.drop_table('payroll_employees')
    op.drop_index(op.f('ix_payroll_email_settings_organization_id'), table_name='payroll_email_settings')
    op.drop_index(op.f('ix_payroll_email_settings_id'), table_name='payroll_email_settings')
    op.drop_table('payroll_email_settings')
    op.drop_index(op.f('ix_payroll_custom_field_definitions_organization_id'), table_name='payroll_custom_field_definitions')
    op.drop_index(op.f('ix_payroll_custom_field_definitions_id'), table_name='payroll_custom_field_definitions')
    op.drop_table('payroll_custom_field_definitions')
    op.drop_index(op.f('ix_payroll_contribution_rates_organization_id'), table_name='payroll_contribution_rates')
    op.drop_index(op.f('ix_payroll_contribution_rates_id'), table_name='payroll_contribution_rates')
    op.drop_table('payroll_contribution_rates')
    op.drop_index(op.f('ix_payroll_compliance_documents_organization_id'), table_name='payroll_compliance_documents')
    op.drop_index(op.f('ix_payroll_compliance_documents_id'), table_name='payroll_compliance_documents')
    op.drop_index(op.f('ix_payroll_compliance_documents_country'), table_name='payroll_compliance_documents')
    op.drop_table('payroll_compliance_documents')
    op.drop_index(op.f('ix_payroll_company_compliance_organization_id'), table_name='payroll_company_compliance')
    op.drop_index(op.f('ix_payroll_company_compliance_id'), table_name='payroll_company_compliance')
    op.drop_table('payroll_company_compliance')
    op.drop_index(op.f('ix_payroll_activity_log_organization_id'), table_name='payroll_activity_log')
    op.drop_index(op.f('ix_payroll_activity_log_id'), table_name='payroll_activity_log')
    op.drop_index(op.f('ix_payroll_activity_log_created_at'), table_name='payroll_activity_log')
    op.drop_table('payroll_activity_log')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_platform_statutory_rates_id'), table_name='platform_statutory_rates')
    op.drop_table('platform_statutory_rates')
    op.drop_index(op.f('ix_platform_settings_key'), table_name='platform_settings')
    op.drop_index(op.f('ix_platform_settings_id'), table_name='platform_settings')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_payroll_jurisdiction_packs_id'), table_name='payroll_jurisdiction_packs')
    op.drop_index('ix_jurisdiction_packs_country_state', table_name='payroll_jurisdiction_packs')
    op.drop_table('payroll_jurisdiction_packs')
    op.drop_index(op.f('ix_organizations_organization_code'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
