"""
engine/jurisdictions/singapore/statutory_summary.py
---------------------------------------------------
Super Admin Singapore statutory configuration summary (Phase 5.6) and the
Singapore report-template catalog. Pure: service.py gathers the facts
(packs, rows, evidence, PWM schedule statistics, templates) and this module
only arranges them into sections. No value here is a statutory rate — every
figure in the output is a persisted row value passed in by the caller; a
missing row is reported as NOT_CONFIGURED, never defaulted.

Report-template classification (ReportTemplate has no classification
column; this catalog is the single source for it, used by the summary API,
the seed script and the tests):
  EXPORT_READY        - a file/extract built to a published layout, which
                        the employer submits itself (IR8A AIS extract, CPF
                        EZPay FTP file). Not a submission, not an approval.
  SUBMISSION_SUPPORT  - figures the employer keys into / reconciles against
                        an official channel (SDL, CPF, SHG totals).
  INTERNAL_REPORT     - operational payroll report (register, summary, levy
                        reconciliation); no official format exists or is claimed.
  STATUTORY_WORKSPACE - internal compliance working view (PWM, LQS, IR21)
                        generated by a dedicated Singapore generator from
                        the existing evaluators (Phase 5.7); the generic
                        payslip-column generator refuses these types.
None of them is certified or approved by CPF Board, IRAS, MOM or PDPC
(`officialCertification` is False for every entry).
"""

from datetime import date
from typing import Optional

from .labour import PWM_KEY_PREFIX, PWM_OT_RATE_PREFIX

CONFIGURED, PARTIAL, NOT_CONFIGURED = "CONFIGURED", "PARTIAL", "NOT_CONFIGURED"
# ReportTemplate.status lifecycle (models.py: Draft | Review | Approved | Published | Active | Superseded).
TEMPLATE_STATUSES = ("Draft", "Review", "Approved", "Published", "Active", "Superseded")
PASS, REVIEW, BLOCKED = "PASS", "REVIEW", "BLOCKED"
NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
EXTERNAL_INTEGRATION_REQUIRED = "EXTERNAL_INTEGRATION_REQUIRED"
READY, TEMPLATE_NOT_ACTIVE, TEMPLATE_MISSING = "READY", "TEMPLATE_NOT_ACTIVE", "TEMPLATE_MISSING"
EXTERNAL_DATA_REQUIRED, EVIDENCE_REQUIRED = "EXTERNAL_DATA_REQUIRED", "EVIDENCE_REQUIRED"
DECISION_RECORDED = "DECISION_RECORDED"
# Evidence lifecycle (final completion programme), derived — never stored as a
# settable status: no artifact -> EVIDENCE_REQUIRED; registered, no document
# -> SUBMITTED; uploaded (server SHA-256), awaiting a distinct reviewer ->
# UNDER_REVIEW; accepted -> PASS (EXPIRED after its validity date);
# rejected -> REJECTED.
SUBMITTED, UNDER_REVIEW, REJECTED, EXPIRED = "SUBMITTED", "UNDER_REVIEW", "REJECTED", "EXPIRED"
SUPERSEDED = "SUPERSEDED"
NOT_APPLICABLE = "NOT_APPLICABLE"
# Readiness-dashboard vocabulary: PASS / BLOCKED / EXTERNAL_REQUIRED / BUSINESS_DECISION_REQUIRED.
EXTERNAL_REQUIRED = "EXTERNAL_REQUIRED"
INTERNAL = "Internal engineering evidence (full suite + PostgreSQL rehearsals, docs/SINGAPORE_FINAL_IMPLEMENTATION_STATUS.md) — not re-run at runtime, not regulator certification"
BUSINESS_DECISION = "BUSINESS_DECISION_REQUIRED"
LQS_QUOTA_PREFIX = "lqs_quota__"            # sourced MOM quota rows, when they exist (none are seeded)

# ZP-SG-ENG-001 §18 production gates — the single source the Super Admin UI
# renders. Zoiko records no gate evidence; the status only moves when real
# external evidence exists (docs/SINGAPORE_FINAL_IMPLEMENTATION_STATUS.md §18).
SG_PRODUCTION_GATES = (
    ("G1", "CPF content certification", "Independent reviewer; CPF Board sources", "Signed independent comparison report",
     "Statutory compliance owner", EVIDENCE_REQUIRED,
     "An independent reviewer signs that CPF rates, ceilings, age bands, OW/AW treatment and the golden vectors match "
     "CPF Board publications"),
    ("G2", "CPF operations (EZPay file, payment, reconciliation)", "CPF Board (EZPay / Corppass)",
     "CPF acknowledgement and payment reconciliation", "Employer payroll operations", EVIDENCE_REQUIRED,
     "A CPF acknowledgement of a real submission, reconciled to the payroll register with zero unexplained variance"),
    ("G3", "IRAS AIS (YA2027 model, route, amendments)", "IRAS", "Signed submission-mode decision; acknowledged "
     "original and modification", "Product owner", BUSINESS_DECISION,
     "D1 recorded, then IRAS acknowledges an original and an amended submission (or export upload)"),
    ("G4", "IR21 tax clearance", "IRAS", "Guidance review; acknowledged filing", "Statutory compliance owner",
     EVIDENCE_REQUIRED, "Compliance review of the IR21 workspace against IRAS guidance plus one acknowledged IR21"),
    ("G5", "Foreign workforce (levy billing, LQS / PWM)", "MOM", "Levy-bill reconciliation; published values",
     "Statutory compliance owner", EVIDENCE_REQUIRED,
     "A MOM levy bill reconciled to computed FWL; the MOM data items resolved or formally scoped out"),
    ("G6", "Labour pay (Employment Act)", "MOM / counsel", "Legal review memo", "Legal and compliance owner",
     EVIDENCE_REQUIRED, "Counsel signs a memo on the Employment Act pay, overtime and deduction rules the product applies"),
    ("G7", "Security / privacy (PDPA, NRIC/FIN)", "PDPC framework (DPO)", "DPO sign-off; security review; recovery test",
     "DPO and security owner", EVIDENCE_REQUIRED,
     "DPO signs; security review has no open high findings; the backup-restore rehearsal is evidenced"),
    ("G8", "Two-cycle parallel payroll and AIS simulation", "Design-partner employer", "Parallel-run reconciliation report",
     "Implementation lead", EVIDENCE_REQUIRED,
     "Two consecutive cycles reconcile against the incumbent payroll, with an AIS simulation"),
)

_NEXT_ACTION = {
    EVIDENCE_REQUIRED: "Register a Source Evidence artifact with form number {tag} and upload the signed document",
    SUBMITTED: "Upload the signed document to the registered artifact (the server records its SHA-256)",
    UNDER_REVIEW: "A Super Admin other than the one who registered it accepts or rejects the evidence",
    REJECTED: "Register a corrected artifact with form number {tag}, upload it and supersede the rejected one",
    EXPIRED: "Register current evidence with form number {tag}, upload it and supersede the expired one",
    PASS: "None",
}
_BLOCKING = {
    EVIDENCE_REQUIRED: "No evidence recorded",
    SUBMITTED: "Evidence registered but no document uploaded",
    UNDER_REVIEW: "Awaiting review by a second Super Admin",
    REJECTED: "The evidence was rejected by its reviewer",
    EXPIRED: "The accepted evidence is past its validity date",
    PASS: None,
}

EXPORT_READY, SUBMISSION_SUPPORT = "EXPORT_READY", "SUBMISSION_SUPPORT"
INTERNAL_REPORT, STATUTORY_WORKSPACE = "INTERNAL_REPORT", "STATUTORY_WORKSPACE"
GENERIC_GENERATOR = "GENERIC_TEMPLATE"      # service.generate_report_from_template over real PayslipItem columns

WP_LEVY_PREFIX = "fwl_wp__"                 # engine/countries/singapore.work_permit_levy_key

_NOT_CERTIFIED = "Internal Zoiko report — not approved or certified by CPF Board, IRAS, MOM or PDPC."

# (templateKey, reportType, name, classification, generator, regulatoryAuthority, description)
SG_REPORT_TEMPLATES = (
    ("SG-IR8A", "SG_IR8A", "IR8A — Employment Income Data Extract (AIS)", EXPORT_READY,
     "POST /api/payroll/singapore/reports/ir8a", "IRAS",
     "EXPORT_READY extract of IR8A employment income per wage year for the employer's own AIS submission "
     "(AIS-API 2.0 or myTax Portal). Never reported as submitted to IRAS. " + _NOT_CERTIFIED),
    ("SG-SDL-MONTHLY", "SG_SDL_MONTHLY", "Skills Development Levy — Monthly Employer Total", SUBMISSION_SUPPORT,
     "POST /api/payroll/singapore/reports/sdl", "CPF Board (SDL collection)",
     "Monthly SDL payable (sum of per-employee SDL, rounded down) for the CPF submission. " + _NOT_CERTIFIED),
    ("SG-CPF-EZPAY", "SG_CPF_EZPAY", "CPF EZPay Contribution File (FTP specification)", EXPORT_READY,
     "POST /api/payroll/singapore/reports/cpf-ezpay", "CPF Board",
     "CPF EZPay (FTP) contribution file built to the published CPF Board specification; the employer uploads "
     "it through CPF EZPay (Corppass). " + _NOT_CERTIFIED),
    ("SG-PAYROLL-REGISTER", "SG_PAYROLL_REGISTER", "Singapore Payroll Register", INTERNAL_REPORT,
     GENERIC_GENERATOR, None,
     "INTERNAL_REPORT — one row per employee for a finalized payroll run: earnings, employee CPF, SHG, "
     "deductions, net pay and employer CPF / SDL / FWL, read from the run's persisted payslip columns. "
     + _NOT_CERTIFIED),
    ("SG-PAYROLL-SUMMARY", "SG_PAYROLL_SUMMARY", "Singapore Payroll Summary", INTERNAL_REPORT,
     GENERIC_GENERATOR, None,
     "INTERNAL_REPORT — run totals (gross pay, employee CPF, SHG, net pay, employer CPF, SDL, FWL) summed "
     "from the run's persisted payslip columns. " + _NOT_CERTIFIED),
    ("SG-CPF-CONTRIBUTION", "SG_CPF_CONTRIBUTION", "CPF Contribution Report", SUBMISSION_SUPPORT,
     GENERIC_GENERATOR, "CPF Board",
     "SUBMISSION_SUPPORT — employee and employer CPF per employee for a finalized run, for reconciliation "
     "against the CPF EZPay submission. Gross pay shown is total gross, not CPF-subject OW/AW (those are in "
     "each payslip's calculation trace). " + _NOT_CERTIFIED),
    ("SG-SHG-MONTHLY", "SG_SHG_MONTHLY", "Self-Help Group Contributions — Monthly", SUBMISSION_SUPPORT,
     GENERIC_GENERATOR, "CPF Board (SHG collection)",
     "SUBMISSION_SUPPORT — SHG deduction per employee for a finalized run, for reconciliation against the "
     "CPF submission (payment codes 02–05). The fund (CDAC/ECF/MBMF/SINDA) is on the employee record and in "
     "the payslip trace, not a report column. " + _NOT_CERTIFIED),
    ("SG-FWL-MONTHLY", "SG_FWL_MONTHLY", "Foreign Worker Levy — Monthly Reconciliation", INTERNAL_REPORT,
     GENERIC_GENERATOR, None,
     "INTERNAL_REPORT — employer levy cost per employee as computed by payroll, for reconciling against the "
     "MOM levy bill. MOM bills the levy; the employer files nothing from this report. " + _NOT_CERTIFIED),
    ("SG-PWM-COMPLIANCE", "SG_PWM_COMPLIANCE", "Progressive Wage Model Compliance Workspace", STATUTORY_WORKSPACE,
     "POST /api/payroll/singapore/reports/pwm-compliance", None,
     "STATUTORY_WORKSPACE — per wage month, each PWM-classified employee's floor and overtime gross "
     "requirement result (MET / SHORTFALL / NOT_EVALUATED) from the same PWM check the run preflight uses, "
     "with the sgp_pwm_overtime_schedules row and its MOM source. Not an MOM submission. " + _NOT_CERTIFIED),
    ("SG-IR21-REGISTER", "SG_IR21_REGISTER", "IR21 Tax Clearance Register", STATUTORY_WORKSPACE,
     "POST /api/payroll/singapore/reports/ir21-register", None,
     "STATUTORY_WORKSPACE — the year's IR21 cases and every case still holding pay, from the sgp_ir21_cases "
     "lifecycle: status, withholding, maker/checker, outstanding action and references. No IR21 tax is "
     "calculated. Not an IRAS filing. " + _NOT_CERTIFIED),
    ("SG-LQS-COMPLIANCE", "SG_LQS_COMPLIANCE", "Local Qualifying Salary Compliance Workspace", STATUTORY_WORKSPACE,
     "POST /api/payroll/singapore/reports/lqs-compliance", None,
     "STATUTORY_WORKSPACE — per wage month, each employee's LQS result as evaluated by the payroll engine "
     "(threshold, wages considered, basis, reference). The MOM foreign-worker quota computation is not "
     "performed. Not an MOM submission. " + _NOT_CERTIFIED),
)
SG_TEMPLATE_KEYS = tuple(t[0] for t in SG_REPORT_TEMPLATES)
# Report types the generic run-based generator must refuse: their subject is
# not a payslip column, so only their dedicated Singapore generator renders them.
SG_DEDICATED_GENERATOR_REPORT_TYPES = frozenset(t[1] for t in SG_REPORT_TEMPLATES if t[3] == STATUTORY_WORKSPACE)


def template_catalog_entry(template_key):
    for key, report_type, name, classification, generator, authority, description in SG_REPORT_TEMPLATES:
        if key == template_key:
            return {"templateKey": key, "reportType": report_type, "name": name, "classification": classification,
                    "generator": generator, "regulatoryAuthority": authority, "description": description,
                    "officialCertification": False}
    return None


def _value(rates, key):
    """A persisted ContributionRate as the caller serialized it, or None."""
    row = rates.get(key)
    if row is None:
        return None
    return {k: row.get(k) for k in ("label", "flatAmount", "employerRatePct", "textValue", "effectiveFrom",
                                    "effectiveTo", "sourceDocumentId")}


def _section(key, label, values, required, sources, notes=None, effective_date=None, status=None):
    present = [k for k in required if values.get(k) is not None]
    if status is None:
        status = CONFIGURED if len(present) == len(required) else (PARTIAL if present else NOT_CONFIGURED)
    return {"key": key, "label": label, "configured": status == CONFIGURED, "status": status,
            "effectiveDate": effective_date, "values": values,
            "missing": [k for k in required if values.get(k) is None],
            "sources": sources, "notes": notes or []}


def _sources_for(values, sources):
    ids = sorted({v["sourceDocumentId"] for v in values.values()
                  if isinstance(v, dict) and v.get("sourceDocumentId") is not None})
    return [sources.get(i, {"id": i, "missing": True}) for i in ids]


def _readiness_item(key, label, status, evidence):
    return {"key": key, "label": label, "status": status, "evidence": evidence}


def _operation(key, label, template_key, templates, lifecycle, controls, channel, external, generator=None):
    """One statutory operation's readiness. `state` is READY only when the
    template has an Active version (a generator refuses anything else); the
    external submission / acknowledgement is never claimed."""
    row = templates.get(template_key)
    active = bool(row and (row["status"] == "Active" or row.get("activeVersionId")))
    return {"key": key, "label": label, "templateKey": template_key,
            "template": ({"status": row["status"], "version": row["version"], "activeVersion": row.get("activeVersion")}
                         if row else None),
            "state": READY if active else (TEMPLATE_NOT_ACTIVE if row else TEMPLATE_MISSING),
            "generator": generator or (template_catalog_entry(template_key) or {}).get("generator"),
            "lifecycle": lifecycle, "controls": controls, "submissionChannel": channel,
            "externalDependency": external}


def _operations_section(ops: dict, templates: dict) -> dict:
    """Statutory operations readiness (IR8A / AIS, IR21, CPF EZPay). The
    lifecycles are the service's own transition constants passed in; the
    controls listed are the ones those services enforce (each covered by a
    test). Nothing here is an IRAS / CPF Board acceptance."""
    items = [
        _operation(
            "ir8a", "IR8A employment income extract", "SG-IR8A", templates, ops.get("ir8aTransitions"),
            ["Active template only", "Payslips' pinned statutory pack recorded", "NRIC/FIN masked (last 4)",
             "IRAS whole-dollar rounding (income down, deductions up)",
             f"Up to {ops.get('ir8aMaxRecordsPerSubmission')} records per myTax Portal submission",
             "Filing recorded by a different operator from the preparer (refusals audited)",
             "One acknowledged original per year; revision / amendment of an acknowledged original"],
            "The employer keys the extract into IRAS myTax Portal and records IRAS's reference here",
            "IRAS acknowledgement (manual); IRAS-validated YA2027 field mapping (G3)"),
        _operation(
            "ais_api", "IRAS AIS-API 2.0 direct submission", "SG-IR8A", templates, None, [],
            "Not built", "EXTERNAL INTEGRATION REQUIRED: IRAS APEX onboarding, Corppass authorisation, API "
            "credentials in a secrets store, sandbox access and the AIS-API 2.0 specification; submission-mode "
            "decision (export only / API / both) is open", generator="Not built"),
        _operation(
            "ir21", "IR21 tax clearance", "SG-IR21-REGISTER", templates, ops.get("ir21Transitions"),
            [f"Hold on the employee's monies while {', '.join(ops.get('ir21HoldStatuses') or [])}",
             f"Distinct approver to move to {', '.join(ops.get('ir21ApproverStatuses') or [])} (refusals audited)",
             "Held payslips excluded from the bank file", "Filed cases excluded from the IR8A extract",
             "Case view carries no NRIC / bank details; register masks NRIC/FIN", "Tenant-scoped case access"],
            "The employer files Form IR21 on myTax Portal and records the filing / IRAS directive here",
            "IRAS clearance directive (manual); IR21 guidance review (G4)"),
        _operation(
            "cpf_ezpay", "CPF EZPay contribution file", "SG-CPF-EZPAY", templates, ops.get("ezpayTransitions"),
            [f"Fixed-length {ops.get('ezpayRecordLength')}-byte records, ASCII only; trailer count / total checked",
             "Distinct, identified approver before download (refusals audited)",
             "File never stored — rebuilt on download and verified against its SHA-256; every download audited",
             "CPF account numbers masked in the stored summary"],
            "The employer uploads the file through CPF EZPay (Corppass) and records CPF Board's outcome here",
            "CPF Board acceptance and payment reconciliation (G2); no CPF Board API is used"),
    ]
    items[1]["state"] = EXTERNAL_INTEGRATION_REQUIRED          # AIS-API: never READY without onboarding
    # Final closure: the integration boundary as a checklist — what must exist
    # before any AIS-API client could be built or enabled. None of it is in the
    # product; no client, endpoint or credential setting exists, so nothing can
    # be submitted (an organisation selecting DIRECT_API is BLOCKED in its own
    # readiness, and the extract is only ever EXPORT_READY).
    items[1]["integrationPrerequisites"] = [
        {"key": "d1_decision", "item": "Owner decision D1 selects API_SUBMISSION or BOTH", "owner": "Product owner",
         "status": BUSINESS_DECISION},
        {"key": "apex_onboarding", "item": "IRAS APEX API-consumer onboarding for the AIS-API 2.0 service",
         "owner": "Product owner with IRAS", "status": EXTERNAL_INTEGRATION_REQUIRED},
        {"key": "specification", "item": "IRAS AIS-API 2.0 specification (payload schema, validation and error codes) "
                                         "registered as a source artifact", "owner": "Product owner with IRAS",
         "status": EXTERNAL_DATA_REQUIRED},
        {"key": "credentials", "item": "APEX client credentials held in a secrets store (never in the database or "
                                       "the repository)", "owner": "Deploy / security owner",
         "status": EXTERNAL_INTEGRATION_REQUIRED},
        {"key": "corppass", "item": "Corppass authorisation by each employer for Zoiko to submit on its behalf",
         "owner": "Each employer", "status": EXTERNAL_INTEGRATION_REQUIRED},
        {"key": "sandbox", "item": "IRAS sandbox access and a passing sandbox submission (original + amendment)",
         "owner": "Implementation lead with IRAS", "status": EXTERNAL_INTEGRATION_REQUIRED},
    ]
    items[1]["credentialsConfigured"] = False
    quota_rows = ops.get("lqsQuotaRows") or 0
    items.append({
        "key": "lqs_quota", "label": "LQS foreign-worker quota", "templateKey": None, "template": None,
        # Fail-safe: no quota figure is ever produced. With no sourced MOM quota
        # rows the blocker is the data; with rows present, the computation.
        "state": NOT_IMPLEMENTED if quota_rows else EXTERNAL_DATA_REQUIRED,
        "generator": "Not built", "lifecycle": None,
        "controls": ["The per-employee LQS floor is evaluated (engine + SG-LQS-COMPLIANCE)",
                     "No quota / dependency-ratio figure is produced anywhere"],
        "submissionChannel": "Not applicable (MOM computes the employer's quota)",
        "externalDependency": (f"{quota_rows} sourced quota row(s) present; computation not implemented" if quota_rows else
                               "EXTERNAL DATA REQUIRED: MOM sector dependency-ratio ceilings, local qualifying "
                               "headcount and part-time weighting rules as sourced reference data "
                               f"(pack rows '{LQS_QUOTA_PREFIX}*'), plus a decision whether Zoiko computes quota"),
    })
    internal = [i for i in items if i["state"] not in (EXTERNAL_INTEGRATION_REQUIRED, EXTERNAL_DATA_REQUIRED,
                                                          NOT_IMPLEMENTED)]
    blocked = sum(1 for i in internal if i["state"] != READY)
    return {"key": "operations", "label": "Statutory operations", "configured": blocked == 0,
            "status": CONFIGURED if blocked == 0 else PARTIAL, "effectiveDate": None,
            "values": {"items": items}, "missing": [i["key"] for i in internal if i["state"] != READY],
            "sources": [], "notes": ["No operation is certified by, or submitted to, IRAS or CPF Board by Zoiko; the "
                                     "external step is always the employer's."]}


def _artifact_status(r: dict, as_of: date) -> str:
    """One artifact's lifecycle state. PASS only for an artifact whose creator
    is on record, with an UPLOADED document (server-computed SHA-256 — never
    a hand-typed hash), accepted by a DIFFERENT user, not rejected, not
    superseded and inside its validity date."""
    if r.get("superseded"):
        return SUPERSEDED
    if r.get("outcome") == REJECTED:
        return REJECTED
    if (r.get("createdById") and r.get("reviewerId") and r["reviewerId"] != r["createdById"]
            and r.get("hasFile") and r.get("sha256") and r.get("reviewedAt")):
        valid_until = r.get("validUntil")
        return EXPIRED if valid_until and date.fromisoformat(valid_until) < as_of else PASS
    return UNDER_REVIEW if r.get("hasFile") and r.get("sha256") else SUBMITTED


# The gate / decision takes its most advanced CURRENT artifact's state.
_STATE_RANK = (PASS, UNDER_REVIEW, SUBMITTED, EXPIRED, REJECTED)


def _evidence_state(rows: list, tag: str, as_of: Optional[date] = None) -> tuple:
    """(state, recorded evidence) for one gate / decision tag; state None
    when no current (non-superseded) artifact exists."""
    as_of = as_of or date.today()
    tagged = [r for r in rows if (r.get("tag") or "").upper() == tag]
    recorded = []
    for r in tagged:
        status = _artifact_status(r, as_of)
        recorded.append({k: r.get(k) for k in ("id", "title", "agency", "sha256", "reviewedAt", "superseded",
                                               "createdById", "reviewerId", "notes", "validUntil", "outcomeBy",
                                               "outcomeAt", "selectedValue", "decisionReason", "decisionMakerId",
                                               "decidedAt")}
                        | {"status": status, "accepted": status == PASS})
    current = [e["status"] for e in recorded if e["status"] != SUPERSEDED]
    state = next((s for s in _STATE_RANK if s in current), None)
    return state, recorded


def _lead(recorded: list, state: str):
    """The current artifact that gives the gate / decision its state (newest first)."""
    return next((e for e in reversed(recorded) if e["status"] == state), None)


def _readiness_dashboard(sections: list, activation: dict, governance: dict, golden) -> list:
    """The sixteen activation categories (PASS / BLOCKED / EXTERNAL_REQUIRED /
    BUSINESS_DECISION_REQUIRED). Runtime facts where the server can
    observe them; the categories only the engineering evidence can prove are
    labelled as such. PRODUCTION_ACTIVATION passes only when everything does."""
    by_key = {s["key"]: s for s in sections}
    templates = by_key["reportTemplates"]["values"]
    ops = [i for i in by_key["operations"]["values"]["items"]
           if i["state"] not in (EXTERNAL_INTEGRATION_REQUIRED, EXTERNAL_DATA_REQUIRED, NOT_IMPLEMENTED)]
    statutory = [by_key[k] for k in ("cpf", "sdl", "shg", "fwl", "lqs", "pwm", "iras", "ir21") if k in by_key]
    db_state = governance.get("database") or {}
    registry = (governance.get("serviceAvailability") or {}).get("availability")
    pack_active = activation["statutoryPack"]["activation"] == "ACTIVE"

    def row(key, label, status, basis, evidence):
        return {"key": key, "label": label, "status": status, "basis": basis, "evidence": evidence}

    missing_objects = db_state.get("missingSgObjects")
    rows = [
        row("engineering", "Engineering", PASS, "internal", INTERNAL),
        row("configuration", "Configuration",
            PASS if all(s["configurationStatus"] == CONFIGURED for s in statutory) else BLOCKED, "runtime",
            ", ".join(f"{s['label']}: {s['configurationStatus']}" for s in statutory)),
        row("super_admin", "Super Admin", PASS, "runtime", "This readiness view is served from the backend summary"),
        row("report_templates", "Report templates", PASS if templates["present"] == templates["expected"] else BLOCKED,
            "runtime", f"{templates['present']} of {templates['expected']} present, {templates['active']} Active"),
        row("generators", "Generators", PASS if all(i["state"] == READY for i in ops) else BLOCKED, "runtime",
            "; ".join(f"{i['label']}: {i['state']}" for i in ops) + " — a generator renders only an Active template"),
        row("security", "Security", PASS, "internal", INTERNAL + "; external review is gate G7"),
        row("tenant_isolation", "Tenant isolation", PASS, "internal", INTERNAL),
        row("database", "Database",
            PASS if missing_objects == [] else BLOCKED, "runtime",
            "Every Singapore table / column present" if missing_objects == [] else
            f"Missing Singapore objects: {missing_objects}" if missing_objects else
            f"Not inspectable ({db_state.get('error')})"),
        row("migration", "Migration", PASS if db_state.get("atHead") else BLOCKED, "runtime",
            f"database {db_state.get('databaseHeads')} vs code {db_state.get('codeHeads')}"),
        # Phase 6.10: the deploy owner's sign-off is ordinary gate evidence
        # (SG_DEPLOYMENT_SIGNOFF_TAG, reviewed by a different Super Admin), so
        # this row can pass on a record instead of never passing at all.
        row("deployment", "Deployment",
            PASS if (activation.get("deploymentSignoff") or {}).get("status") == PASS else EXTERNAL_REQUIRED, "owner",
            "Deploy-owner review of scripts/deploy_migrate.sh and execution of docs/SINGAPORE_PRODUCTION_ACTIVATION_RUNBOOK.md"
            + f" — sign-off evidence {SG_DEPLOYMENT_SIGNOFF_TAG}: "
            + ((activation.get("deploymentSignoff") or {}).get("status") or EVIDENCE_REQUIRED)),
        row("testing", "Testing", PASS if golden and golden.get("status") == "PASS" else BLOCKED, "runtime",
            f"Latest SG golden-vector run: {golden['status']} {golden['passedCases']}/{golden['totalCases']}"
            if golden else "No SG golden-vector run recorded in this database"),
        row("external_evidence", "External evidence",
            PASS if all(g["status"] == PASS for g in activation["productionGates"]) else EXTERNAL_REQUIRED, "runtime",
            ", ".join(f"{g['key']}: {g['status']}" for g in activation["productionGates"])),
        row("business_decisions", "Business decisions",
            PASS if all(d["status"] == DECISION_RECORDED for d in activation["pendingDecisions"])
            else BUSINESS_DECISION, "runtime",
            ", ".join(f"{d['key']}: {d['status']}" for d in activation["pendingDecisions"])),
        row("external_data", "External data",
            EXTERNAL_REQUIRED if any(d["status"] == EXTERNAL_DATA_REQUIRED for d in activation["externalDependencies"])
            else PASS,
            "runtime", ", ".join(d["key"] for d in activation["externalDependencies"]
                                 if d["status"] == EXTERNAL_DATA_REQUIRED) or "none"),
        row("external_integrations", "External integrations",
            EXTERNAL_REQUIRED if any(d["status"] == EXTERNAL_INTEGRATION_REQUIRED
                                     for d in activation["externalDependencies"]) else PASS,
            "runtime", "; ".join(d["label"] for d in activation["externalDependencies"]
                                 if d["status"] == EXTERNAL_INTEGRATION_REQUIRED) or "none"),
    ]
    blockers = [r["label"] for r in rows if r["status"] != PASS]
    if not pack_active:
        blockers.append("no Active Singapore statutory pack")
    if registry != "AVAILABLE":
        blockers.append(f"service registry {registry or 'missing'}")
    rows.append(row("production_activation", "Production activation", PASS if not blockers else BLOCKED, "runtime",
                    "All categories pass, pack Active, registry AVAILABLE" if not blockers else
                    "Blocked by: " + "; ".join(blockers)))
    return rows


def _service_registry_item(availability):
    """Commercial availability — the owner's PLANNED -> AVAILABLE step, never a
    consequence of pack activation (tax_resolver fails closed without a row)."""
    if availability is None:
        return _readiness_item("service_registry", "Singapore service registry", BLOCKED,
                               "No registry row — onboarding stays closed (fail-closed); the canonical seed creates it "
                               "as PLANNED.")
    state = availability.get("availability")
    return _readiness_item("service_registry", "Singapore service registry", PASS if state == "AVAILABLE" else BLOCKED,
                           f"{state} — onboarding " + ("open" if state == "AVAILABLE" else
                                                        "closed until the owner makes Singapore AVAILABLE after G1–G8"))


# Phase 6.10 — the owner's PLANNED -> AVAILABLE step, gated (Singapore only).
# Before this, the registry row had no API at all: opening onboarding meant a
# raw database UPDATE with no audit row and no check that any gate had passed.
# The requirements below are derived from this summary alone (server-side,
# never client-supplied) and service.transition_sg_service_registry re-derives
# them at the moment of the change. Every requirement is fail-closed: an owner
# who wants a narrower launch set (e.g. G2/G5/G8 collected during a pilot) needs
# a recorded decision and a reviewed code change, not a switch.
SG_DEPLOYMENT_SIGNOFF_TAG = "SG-OPS-DEPLOYMENT"
SG_REGISTRY_OPEN, SG_REGISTRY_CLOSED = "AVAILABLE", "PLANNED"


def registry_transition_requirements(sections: list, activation: dict) -> list:
    """What must hold before Singapore may be made AVAILABLE. Each item is
    {key, label, met, detail}."""
    by_key = {s["key"]: s for s in sections}
    dash = {r["key"]: r for r in activation["readinessDashboard"]}
    pack = activation["statutoryPack"]
    templates = by_key["reportTemplates"]["values"]["templates"]
    missing_active = [t["templateKey"] for t in templates if not t["generatable"]]
    hotfix = pack.get("hotfixPolicy") or {}

    def req(key, label, met, detail):
        return {"key": key, "label": label, "met": bool(met), "detail": detail}

    items = [
        req("pack_active", "An Active Singapore statutory pack is in force", pack["activation"] == "ACTIVE",
            f"{pack.get('packId') or 'no pack'} v{pack.get('version') or '—'} {pack.get('status') or ''}".strip()),
        req("golden_vectors", "Latest Singapore golden-vector run is PASS", dash["testing"]["status"] == PASS,
            dash["testing"]["evidence"]),
        req("templates_active", "Every Singapore report template has an Active version", not missing_active,
            "All Active" if not missing_active else "Not Active: " + ", ".join(missing_active)),
        req("configuration", "Statutory configuration complete", dash["configuration"]["status"] == PASS,
            dash["configuration"]["evidence"]),
        req("database", "Every Singapore table / column present", dash["database"]["status"] == PASS,
            dash["database"]["evidence"]),
        req("migration", "Database at the code's Alembic head", dash["migration"]["status"] == PASS,
            dash["migration"]["evidence"]),
    ]
    items += [req(f"gate_{g['key']}", f"{g['key']} {g['label']}: evidence accepted", g["status"] == PASS, g["status"])
              for g in activation["productionGates"]]
    items += [req(f"decision_{d['key']}", f"{d['key']} {d['label']}: decision recorded, and in force",
                  d["status"] == DECISION_RECORDED and not d.get("inForceDiffers"),
                  d["status"] if d["status"] != DECISION_RECORDED else
                  (f"recorded {d.get('recordedValue')} differs from {d.get('inForceValue')} in force — the code change "
                   "is not made" if d.get("inForceDiffers") else f"recorded {d.get('recordedValue')}"))
              for d in activation["pendingDecisions"]]
    items += [
        req("deployment_signoff", f"Deploy-owner sign-off accepted ({SG_DEPLOYMENT_SIGNOFF_TAG})",
            dash["deployment"]["status"] == PASS, (activation.get("deploymentSignoff") or {}).get("status")
            or EVIDENCE_REQUIRED),
        req("no_unreviewed_hotfix", "No Singapore hotfix awaiting its review", not hotfix.get("unreviewedHotfixes"),
            f"{hotfix.get('unreviewedHotfixes') or 0} awaiting review"),
    ]
    return items


def _registry_transition(sections: list, activation: dict) -> dict:
    current = (activation.get("serviceAvailability") or {}).get("availability")
    requirements = registry_transition_requirements(sections, activation)
    unmet = [r for r in requirements if not r["met"]]
    return {"current": current, "targets": [SG_REGISTRY_OPEN, SG_REGISTRY_CLOSED],
            "requirements": requirements, "unmet": len(unmet),
            "availableAllowed": current == SG_REGISTRY_CLOSED and not unmet,
            "plannedAllowed": current == SG_REGISTRY_OPEN,
            "note": "Server-derived. Making Singapore AVAILABLE opens onboarding to every prospective Singapore "
                    "employer (there is no pilot / allow-list mode); PLANNED closes it again."}


def _pending_decisions(governance: dict) -> list:
    """Owner decisions D1–D3 with the value currently in force. Nothing here
    chooses an option; an item leaves the list only when the owner records the
    decision (docs/SINGAPORE_FINAL_IMPLEMENTATION_STATUS.md §20)."""
    ais = governance.get("aisSubmissionModeSetting") or {}
    hotfix = governance.get("hotfixPolicy") or {}
    scope = governance.get("controlScope") or {}
    # D3 asks whether these controls widen to EVERY jurisdiction. A country
    # that opts in under its own specification (Sweden, ZP-SE-ENG-001 §14/§16)
    # does not decide D3: every set still holds SG and none is platform-wide,
    # so SG_ONLY stays the value in force and the opt-ins are named.
    opt_ins = sorted({c for v in scope.values() for c in v} - {"SG"})
    sg_only = bool(scope) and all("SG" in v for v in scope.values())
    return [
        {"key": "D1", "label": "IR8A / AIS submission mode offered by the product",
         "options": ["EXPORT_ONLY", "API_SUBMISSION", "BOTH"],
         "inForce": "EXPORT_ONLY (built); per-organisation setting options: " + ", ".join(ais.get("options") or []),
         "inForceValue": "EXPORT_ONLY",
         "effectIfDifferent": "API_SUBMISSION / BOTH need the IRAS AIS-API 2.0 integration (external onboarding; not built)",
         "status": BUSINESS_DECISION},
        {"key": "D2", "label": "Singapore hotfix policy", "options": hotfix.get("options") or [],
         "inForce": hotfix.get("current"), "inForceValue": hotfix.get("current"),
         "effectIfDifferent": "SG_HOTFIX_POLICY is a code constant — a recorded different policy needs a reviewed code change",
         "status": BUSINESS_DECISION},
        {"key": "D3", "label": "Scope of the Singapore-only governance controls", "options": ["SG_ONLY", "ALL_COUNTRIES"],
         "inForce": (("SG_ONLY" + (f" (plus per-country opt-ins: {', '.join(opt_ins)})" if opt_ins else ""))
                     if sg_only else scope),
         "inForceValue": "SG_ONLY" if sg_only else None,
         "effectIfDifferent": "ALL_COUNTRIES widens the opt-in control sets to every jurisdiction — a separate "
                              "cross-jurisdiction change with its own review",
         "status": BUSINESS_DECISION},
    ]


def _external_dependencies(rates: dict, activation: dict, sections: list) -> list:
    """What only an authority / external party can supply — derived from the
    current configuration (an item disappears once its data or evidence is
    recorded), never a claim that something is complete."""
    deps = [{"key": "ais_api", "label": "IRAS AIS-API 2.0 (APEX onboarding, Corppass, credentials, sandbox, specification)",
             "authority": "IRAS", "status": EXTERNAL_INTEGRATION_REQUIRED}]
    for key, label in (("fwl_s_pass_end_day_basis", "Whether the pass EXPIRY day is levied (S Pass / Work Permit) — "
                                                     "cancellation is sourced (MOM: levy stops 1 day before cancellation)"),
                       ("lqs_part_time_hourly", "Part-time LQS hourly rate")):
        if rates.get(key) is None:
            deps.append({"key": key, "label": label, "authority": "MOM", "status": EXTERNAL_DATA_REQUIRED})
    if rates.get("cpf_leap_day_birthday_basis") is None:          # Phase 6.10 (engine BLOCKS those months)
        deps.append({"key": "cpf_leap_day_birthday_basis",
                     "label": "Whether a 29 February birthday is observed on 28 February or 1 March in a non-leap year "
                              "(decides the month a 55/60/65/70 CPF age band starts) — those two months are BLOCKED",
                     "authority": "CPF Board", "status": EXTERNAL_DATA_REQUIRED})
    if not any(k.startswith(LQS_QUOTA_PREFIX) for k in rates):
        deps.append({"key": "lqs_quota", "label": "Foreign-worker quota tables (dependency ratios, headcount rules)",
                     "authority": "MOM", "status": EXTERNAL_DATA_REQUIRED})
    deps.append({"key": "unpublished_values",
                 "label": "Values MOM has not published: the Work Permit levy before 24 Sep 2026 outside construction "
                          "(no effective date is stated for the current rates) — pack rows stay BLOCKED, never defaulted",
                 "authority": "MOM", "status": EXTERNAL_DATA_REQUIRED})
    if activation["statutoryPack"]["externalValidation"] == "EXTERNAL_VALIDATION_REQUIRED":
        deps.append({"key": "gates", "label": "Production gates G1–G8 evidence", "authority": "CPF Board / IRAS / MOM / PDPC / reviewers",
                     "status": EVIDENCE_REQUIRED})
    return deps


def build_statutory_summary(facts: dict) -> dict:
    as_of = facts["as_of"]
    active, review = facts.get("active_pack"), facts.get("review_pack")
    values_pack = active or review
    rates, slabs, sources = facts.get("rates") or {}, facts.get("slabs") or {}, facts.get("sources") or {}
    effective = values_pack.get("effectiveFrom") if values_pack else None

    def val(key):
        return _value(rates, key)

    def count_prefix(prefix):
        return sum(1 for k in rates if k.startswith(prefix))

    sections = []

    cpf = {"owCeilingMonthly": val("cpf_ow_ceiling_monthly"), "annualWageCeiling": val("cpf_annual_wage_ceiling"),
           "ageBandSemantics": val("cpf_age_band_semantics"),
           "enforcementDayFollowingMonth": val("cpf_enforcement_day_following_month"),
           "rateBands": slabs.get("cpf_bands") or None, "cohorts": slabs.get("cpf_cohorts") or None}
    sections.append(_section(
        "cpf", "CPF", cpf, ("owCeilingMonthly", "annualWageCeiling", "rateBands"), _sources_for(cpf, sources),
        notes=["The AW ceiling is not a stored value: it is derived per employee as the annual wage ceiling less "
               "the total OW subject to CPF for the year (see the annualWageCeiling row label)."],
        effective_date=effective))

    sdl = {"rate": val("sdl"), "minimumMonthly": val("sdl_min_monthly"), "maximumMonthly": val("sdl_max_monthly")}
    sections.append(_section("sdl", "SDL", sdl, ("rate", "minimumMonthly", "maximumMonthly"),
                             _sources_for(sdl, sources), effective_date=effective))

    shg = {"fundBands": slabs.get("shg_bands") or None, "funds": slabs.get("shg_funds") or None,
           "fundCount": len(slabs.get("shg_funds") or []) or None}
    sections.append(_section("shg", "SHG", shg, ("fundBands", "funds"),
                             [sources[i] for i in slabs.get("shg_source_ids", []) if i in sources],
                             effective_date=effective))

    fwl = {"sPassMonthly": val("fwl_s_pass_monthly"), "workPermitLevyRows": count_prefix(WP_LEVY_PREFIX) or None,
           "paymentDueDay": val("fwl_payment_due_day"), "sPassEndDayBasis": val("fwl_s_pass_end_day_basis"),
           "sPassCancellationEndDayBasis": val("fwl_s_pass_cancellation_end_day_basis"),
           "workPermitCancellationEndDayBasis": val("fwl_work_permit_cancellation_end_day_basis")}
    fwl_notes = []
    if fwl["sPassEndDayBasis"] is None:
        fwl_notes.append("The EXPIRY end-day rule is not published by MOM (fwl_s_pass_end_day_basis / "
                         "fwl_work_permit_end_day_basis not seeded) — a pass EXPIRING mid-month, or ending with no "
                         "recorded end reason, stays BLOCKED. A CANCELLED pass uses the MOM-sourced cancellation rule.")
    sections.append(_section("fwl", "FWL", fwl, ("sPassMonthly", "workPermitLevyRows"), _sources_for(fwl, sources),
                             notes=fwl_notes, effective_date=effective))

    lqs = {"fullTimeMonthly": val("lqs_full_time_monthly"), "partTimeHourly": val("lqs_part_time_hourly")}
    sections.append(_section(
        "lqs", "LQS", lqs, ("fullTimeMonthly", "partTimeHourly"), _sources_for(lqs, sources),
        notes=["The LQS floor is evaluated per employee (payroll engine and the SG-LQS-COMPLIANCE report). The MOM "
               "foreign-worker quota (local qualifying headcount, part-time weighting, sector dependency ratio "
               "ceilings) is NOT IMPLEMENTED — EXTERNAL DATA REQUIRED: MOM's sector quota tables and headcount rules "
               "as sourced reference data, and a decision whether Zoiko should compute quota at all."],
        effective_date=effective))
    # What the platform does NOT do is a capability, not a configured value —
    # kept out of `values` (which only ever holds persisted rows).
    sections[-1]["capabilities"] = {"quotaComputation": NOT_IMPLEMENTED}

    pwm_table = facts.get("pwm_schedule") or {}
    pwm = {"floorRows": count_prefix(PWM_KEY_PREFIX) or None, "overtimeRateRows": count_prefix(PWM_OT_RATE_PREFIX) or None,
           "overtimeSchedule": pwm_table or None}
    sections.append(_section(
        "pwm", "PWM", pwm, ("floorRows", "overtimeSchedule"),
        [sources[i] for i in pwm_table.get("sourceDocumentIds", []) if i in sources],
        notes=["Overtime gross requirements are statutory reference data in sgp_pwm_overtime_schedules "
               "(tenant-independent, read-only); they are not pack rows and are not copied into payslips.",
               "Retail 3-month averaging (MOM Tripartite Cluster for Retail report, Aug 2025, Annex D) is evaluated "
               "by SG-PWM-COMPLIANCE for a retail shortfall, from each month's own payslip (recorded job level, gross "
               "wages, overtime hours). Months it cannot evaluate (part-time, an incomplete month other than the "
               "first, a payslip calculated before the per-month classification was recorded) leave the shortfall "
               "flagged — never assumed met."],
        effective_date=effective))
    sections[-1]["capabilities"] = {"retailThreeMonthAveraging": "IMPLEMENTED"}

    ais_calendar = facts.get("ais_calendar")
    iras = {"aisMandatoryEmployeeThreshold": val("ais_mandatory_employee_threshold"),
            "aisSubmissionMode": val("ais_submission_mode"), "aisFilingCalendar": ais_calendar,
            "retentionYearsFromYa": val("retention_iras_years_from_ya")}
    sections.append(_section(
        "iras", "IRAS (AIS / IR8A)", iras, ("aisMandatoryEmployeeThreshold", "aisSubmissionMode", "aisFilingCalendar"),
        _sources_for(iras, sources),
        notes=["IR8A is an EXPORT_READY extract keyed into myTax Portal by the employer; no AIS-API submission is "
               "built (EXTERNAL INTEGRATION REQUIRED — see Statutory operations)."], effective_date=effective))

    ir21 = {"departureTriggerMonths": val("ir21_departure_trigger_months"),
            "filingLeadMonths": val("ir21_filing_lead_months")}
    sections.append(_section("ir21", "IR21", ir21, ("departureTriggerMonths", "filingLeadMonths"),
                             _sources_for(ir21, sources),
                             notes=["IR21 cases are per organization (sgp_ir21_cases) and are not shown here."],
                             effective_date=effective))

    templates = {t["templateKey"]: t for t in facts.get("templates") or []}
    ezpay_template = templates.get("SG-CPF-EZPAY")
    ezpay = {"template": ({"status": ezpay_template["status"], "version": ezpay_template["version"]}
                          if ezpay_template else None),
             "enforcementDayFollowingMonth": val("cpf_enforcement_day_following_month")}
    sections.append(_section("ezpay", "CPF EZPay", ezpay, ("template",), _sources_for(ezpay, sources),
                             notes=["The employer uploads the file through CPF EZPay (Corppass); no direct CPF "
                                    "Board API is claimed."], effective_date=effective))

    # Draft values are never presented as in force: a section whose values
    # come from a non-Active pack keeps its completeness in
    # configurationStatus but is BLOCKED (Phase 5.7).
    for s in sections:
        s["configurationStatus"] = s["status"]
        s["inForce"] = bool(active) and s["status"] != NOT_CONFIGURED
        if not active and s["status"] in (CONFIGURED, PARTIAL):
            s["status"], s["configured"] = BLOCKED, False
            s["notes"] = s["notes"] + [
                f"Values are from {review['packId']} v{review['version']} ({review['status']}) — not in force until a "
                "Singapore pack is Active." if review else "No Singapore tax pack covers this date — not in force."]
        # Phase 5.8 — per-component lifecycle / validation / evidence state.
        # lifecycleState is the pack the values come from; validationState is
        # EXTERNAL_VALIDATION_REQUIRED until the §18 production gates are
        # evidenced (none is recorded in Zoiko), whatever the internal review.
        s["lifecycleState"] = ((values_pack["status"] or "").upper() if values_pack and s["configurationStatus"] != NOT_CONFIGURED
                               else NOT_CONFIGURED)
        s["validationState"] = "EXTERNAL_VALIDATION_REQUIRED"
        s["sourcesReviewed"] = f"{sum(1 for x in s['sources'] if x.get('reviewed'))}/{len(s['sources'])}"
        s["effectiveTo"] = values_pack.get("effectiveTo") if values_pack else None
        s["lastRetrievedAt"] = max((x["retrievedAt"] for x in s["sources"] if x.get("retrievedAt")), default=None)

    template_rows = []
    for key in SG_TEMPLATE_KEYS:
        entry = template_catalog_entry(key)
        row = templates.get(key)
        template_rows.append({
            **{k: entry[k] for k in ("templateKey", "reportType", "classification", "generator", "officialCertification")},
            "name": row["name"] if row else entry["name"],
            "present": row is not None,
            "id": row["id"] if row else None, "status": row["status"] if row else None,
            "version": row["version"] if row else None, "effectiveFrom": row["effectiveFrom"] if row else None,
            "documentScope": row["documentScope"] if row else None,
            # Lifecycle evidence (Phase 5.7): the approver is a column; the
            # approval / status-change times come from the audit trail.
            **{k: (row.get(k) if row else None) for k in (
                "approvedById", "approvedAt", "lastStatusChangeAt", "auditEntries", "versionCount",
                "previousVersionId", "sourceDocumentId", "sourceReferences", "regulatoryAuthority", "description",
                "updatedAt", "allowedNextStatuses", "effectiveTo", "activeVersion", "activeVersionId")},
            "regulatoryAuthorityCatalog": entry["regulatoryAuthority"],
            "source": sources.get(row["sourceDocumentId"]) if row and row.get("sourceDocumentId") else None,
            "editable": (row["status"] in ("Draft", "Review", "Approved")) if row else None,
            # No template is externally validated by CPF Board / IRAS / MOM.
            "externalValidation": "EXTERNAL_VALIDATION_REQUIRED",
            # A generator renders the Active version, which may not be the listed (latest) one.
            "generatable": bool(row and (row["status"] == "Active" or row.get("activeVersionId"))),
        })
    unexpected = sorted(k for k in templates if k not in SG_TEMPLATE_KEYS)
    missing_templates = [r["templateKey"] for r in template_rows if not r["present"]]
    sections.append({
        "key": "reportTemplates", "label": "Reporting",
        "configured": not missing_templates,
        "status": CONFIGURED if not missing_templates else (PARTIAL if len(missing_templates) < len(template_rows)
                                                            else NOT_CONFIGURED),
        "effectiveDate": None,
        "values": {"expected": len(template_rows), "present": len(template_rows) - len(missing_templates),
                   "active": sum(1 for r in template_rows if r["status"] == "Active"),
                   # Every lifecycle state the ReportTemplate model defines; this repo has no
                   # "Deprecated" state — a retired version is Superseded.
                   "statusCounts": {st: sum(1 for r in template_rows if r["status"] == st) for st in TEMPLATE_STATUSES},
                   "generatorTypes": len({r["reportType"] for r in template_rows}),
                   "templates": template_rows, "unexpectedTemplateKeys": unexpected},
        "missing": missing_templates, "sources": [],
        "notes": ["Classification is Zoiko's own; no template is certified by CPF Board, IRAS, MOM or PDPC."],
    })

    sections.append(_operations_section(
        {**(facts.get("operations") or {}), "lqsQuotaRows": count_prefix(LQS_QUOTA_PREFIX)}, templates))

    unreviewed = [s for s in sources.values() if not s.get("reviewed")]
    golden = facts.get("latest_golden")
    items = [
        _readiness_item("active_pack", "Active Singapore tax pack on the date",
                        PASS if active else BLOCKED,
                        f"{active['packId']} v{active['version']}" if active else
                        ("No Active pack — values shown are from "
                         f"{review['packId']} v{review['version']} ({review['status']}), not in force"
                         if review else "No Singapore tax pack covers this date")),
        _readiness_item("statutory_sections", "Statutory sections configured",
                        PASS if all(s["configured"] for s in sections if s["key"] not in ("reportTemplates", "operations"))
                        else REVIEW,
                        ", ".join(f"{s['label']}: {s['status']}" for s in sections
                                  if s["key"] not in ("reportTemplates", "operations"))),
        _readiness_item("source_evidence", "Source evidence reviewed",
                        PASS if sources and not unreviewed else REVIEW,
                        f"{len(sources) - len(unreviewed)} of {len(sources)} linked source artifacts reviewed"),
        _readiness_item("report_templates", "Singapore report templates present",
                        PASS if not missing_templates else REVIEW,
                        f"{len(template_rows) - len(missing_templates)} of {len(template_rows)} present"
                        + (f"; missing {', '.join(missing_templates)}" if missing_templates else "")),
        _readiness_item("golden_vectors", "Latest Singapore golden-vector certification run",
                        PASS if golden and golden.get("status") == "PASS" else REVIEW,
                        (f"{golden['status']} {golden['passedCases']}/{golden['totalCases']} at {golden['runAt']}"
                         if golden else "No run recorded")),
        _readiness_item("production_gates", "ZP-SG-ENG-001 §18 production gates G1–G8", BLOCKED,
                        "No gate evidence is recorded in Zoiko; external evidence is required."),
        _service_registry_item((facts.get("governance") or {}).get("serviceAvailability")),
    ]
    overall = BLOCKED if any(i["status"] == BLOCKED for i in items) else (
        REVIEW if any(i["status"] == REVIEW for i in items) else PASS)
    sections.append({"key": "readiness", "label": "Readiness", "configured": overall == PASS, "status": overall,
                     "effectiveDate": None, "values": {"items": items}, "missing": [], "sources": [], "notes": []})

    pack_status = CONFIGURED if active else (BLOCKED if review else NOT_CONFIGURED)
    sections.insert(0, {
        "key": "pack", "label": "Statutory Pack", "configured": bool(active), "status": pack_status,
        "configurationStatus": CONFIGURED if values_pack else NOT_CONFIGURED, "inForce": bool(active),
        "effectiveDate": effective,
        "values": {"activePack": active, "valuesFromPack": values_pack, "valuesFromActivePack": bool(active),
                   "versions": facts.get("packs") or []},
        "missing": [] if active else ["activePack"], "sources": [],
        "notes": ([] if active else
                  [f"No Active Singapore pack on {as_of.isoformat()}"
                   + (f" — {review['packId']} v{review['version']} is {review['status']}; its values are shown for "
                      "review only and are not in force." if review else ".")]),
    })

    # Phase 5.8 — activation readiness (read-only; nothing is activated here).
    # Gates mirror service.set_jurisdiction_pack_status for SG tax packs.
    pack_source = sources.get(values_pack["sourceDocumentId"]) if values_pack and values_pack.get("sourceDocumentId") else None
    template_values = next(x for x in sections if x["key"] == "reportTemplates")["values"]
    pwm_values = next(x for x in sections if x["key"] == "pwm")["values"].get("overtimeSchedule") or {}
    activation = {
        "statutoryPack": {
            "status": values_pack["status"] if values_pack else None,
            "packId": values_pack["packId"] if values_pack else None,
            "version": values_pack["version"] if values_pack else None,
            "effectiveFrom": values_pack["effectiveFrom"] if values_pack else None,
            "source": ({k: pack_source.get(k) for k in ("id", "agency", "title", "url", "reviewed")} if pack_source else None),
            "sourceHash": pack_source.get("sha256") if pack_source else None,
            "approval": {"approvedById": values_pack.get("approvedById") if values_pack else None,
                         "distinctFromLastEditor": bool(values_pack and values_pack.get("approvedById")
                                                        and values_pack.get("approvedById") != values_pack.get("updatedById"))},
            "activation": "ACTIVE" if active else "NOT_ACTIVE",
            "activationGates": [
                {"key": "distinct_approver", "met": bool(values_pack and values_pack.get("approvedById")
                                                         and values_pack.get("approvedById") != values_pack.get("updatedById"))},
                {"key": "source_evidence_linked", "met": bool(values_pack and values_pack.get("sourceDocumentId"))},
                {"key": "effective_from_set", "met": bool(values_pack and values_pack.get("effectiveFrom"))},
                {"key": "latest_golden_run_pass", "met": bool(golden and golden.get("status") == "PASS")},
            ],
            "externalValidation": "EXTERNAL_VALIDATION_REQUIRED",
            "lastEditedById": values_pack.get("updatedById") if values_pack else None,
            "hotfixPolicy": (facts.get("governance") or {}).get("hotfixPolicy"),
            "effectiveTo": values_pack.get("effectiveTo") if values_pack else None,
            "audit": facts.get("pack_audit"),
        },
        "reportTemplates": {"total": template_values["present"], **template_values["statusCounts"]},
        "pwm": {"rows": pwm_values.get("totalRows"), "schedules": pwm_values.get("schedules"),
                "sourceDocuments": len(pwm_values.get("sourceDocumentIds") or []),
                "latestRetrieved": pwm_values.get("latestRetrievedAt"), "lastSeeded": pwm_values.get("lastSeededAt")},
    }

    governance = facts.get("governance") or {}
    activation["serviceAvailability"] = governance.get("serviceAvailability")
    activation["aisSubmissionModeSetting"] = governance.get("aisSubmissionModeSetting")
    activation["pendingDecisions"] = _pending_decisions(governance)
    activation["externalDependencies"] = _external_dependencies(rates, activation, sections)
    evidence_rows = governance.get("evidence") or []
    decision_state = {d["key"]: _evidence_state(evidence_rows, f"SG-DECISION-{d['key']}", as_of)
                      for d in activation["pendingDecisions"]}
    for d in activation["pendingDecisions"]:
        state, recorded = decision_state[d["key"]]
        tag = f"SG-DECISION-{d['key']}"
        lead = _lead(recorded, state) if state else None
        # A decision counts only as an ACCEPTED memo that carries its selected
        # option (record_sg_decision) — a memo alone records no choice.
        no_value = state == PASS and not (lead or {}).get("selectedValue")
        if no_value:
            state, lead = None, None
        d["evidenceRecorded"] = recorded
        d["evidenceTag"] = tag
        d["reviewStatus"] = state or EVIDENCE_REQUIRED
        d["recordedValue"] = (lead or {}).get("selectedValue")
        d["decisionMakerId"] = (lead or {}).get("decisionMakerId") or (lead or {}).get("createdById")
        d["decidedAt"] = (lead or {}).get("decidedAt")
        d["reason"] = (lead or {}).get("decisionReason")
        d["reviewerId"] = (lead or {}).get("reviewerId") or (lead or {}).get("outcomeBy")
        d["reviewedAt"] = (lead or {}).get("reviewedAt") or (lead or {}).get("outcomeAt")
        if state == PASS:
            d["status"] = DECISION_RECORDED
            in_force = d.get("inForceValue")
            d["inForceDiffers"] = bool(in_force and d["recordedValue"] != in_force)
        elif state in (SUBMITTED, UNDER_REVIEW, REJECTED, EXPIRED):
            d["status"] = state
        d["blockingReason"] = (None if d["status"] == DECISION_RECORDED else
                               "The accepted memo records no selected option — record the decision" if no_value else
                               _BLOCKING.get(state) or "No decision recorded — the value in force is the product default")
        d["nextAction"] = ("None" if d["status"] == DECISION_RECORDED else
                           "Record the decision (selected option + reason), upload the signed memo; a second Super Admin "
                           "accepts it" if state is None else _NEXT_ACTION[state].format(tag=tag))
    gates = []
    for k, label, authority, evidence, owner, status, criterion in SG_PRODUCTION_GATES:
        tag = f"SG-GATE-{k}"
        state, recorded = _evidence_state(evidence_rows, tag, as_of)
        if k == "G3" and decision_state["D1"][0] == PASS and status == BUSINESS_DECISION:
            status = EVIDENCE_REQUIRED                       # D1 recorded; the IRAS evidence is still needed
        shown = state or status
        lead = _lead(recorded, state) if state else None
        gates.append({"key": k, "label": label, "authority": authority, "evidenceRequired": evidence, "owner": owner,
                      "requiredArtifact": evidence, "validationCriteria": criterion,
                      "status": shown, "evidenceRecorded": recorded or None, "evidenceTag": tag,
                      "submittedArtifactId": (lead or {}).get("id"),
                      "reviewedBy": (lead or {}).get("reviewerId") or (lead or {}).get("outcomeBy"),
                      "reviewDate": (lead or {}).get("reviewedAt") or (lead or {}).get("outcomeAt"),
                      "expiryDate": (lead or {}).get("validUntil"), "notes": (lead or {}).get("notes"),
                      "blockingReason": (_BLOCKING.get(shown) if shown in _BLOCKING else
                                         "Owner decision D1 not recorded" if shown == BUSINESS_DECISION else None),
                      "nextAction": (_NEXT_ACTION[shown].format(tag=tag) if shown in _NEXT_ACTION else
                                     "Record decision D1 (AIS submission mode) first")})
    activation["productionGates"] = gates
    # Phase 6.10 activation gates (mirrors service._sg_activation_evidence_refusal).
    g1 = next(g for g in gates if g["key"] == "G1")
    golden_check = facts.get("pack_golden_check")
    starts = (values_pack or {}).get("effectiveFrom")
    activation["statutoryPack"]["packGoldenCheck"] = golden_check
    activation["statutoryPack"]["activationGates"] += [
        {"key": "g1_evidence_accepted", "met": g1["status"] == PASS},
        {"key": "pack_reproduces_golden_vectors",
         "met": bool(golden_check and golden_check["casesInWindow"] and not golden_check["failures"])},
        {"key": "effective_from_first_of_month", "met": bool(starts and str(starts).endswith("-01"))},
    ]
    deploy_state, deploy_recorded = _evidence_state(evidence_rows, SG_DEPLOYMENT_SIGNOFF_TAG, as_of)
    deploy_lead = _lead(deploy_recorded, deploy_state) if deploy_state else None
    activation["deploymentSignoff"] = {
        "evidenceTag": SG_DEPLOYMENT_SIGNOFF_TAG, "status": deploy_state or EVIDENCE_REQUIRED,
        "evidenceRecorded": deploy_recorded or None, "submittedArtifactId": (deploy_lead or {}).get("id"),
        "reviewedBy": (deploy_lead or {}).get("reviewerId") or (deploy_lead or {}).get("outcomeBy"),
        "requiredArtifact": "Deploy-owner sign-off: runbook A6/A7 and B–D complete, production runtime verified "
                            "(deployed commit, service healthy, database at head, drift check clean)",
        "blockingReason": _BLOCKING.get(deploy_state or EVIDENCE_REQUIRED),
        "nextAction": _NEXT_ACTION[deploy_state or EVIDENCE_REQUIRED].format(tag=SG_DEPLOYMENT_SIGNOFF_TAG)}
    activation["readinessDashboard"] = _readiness_dashboard(sections, activation, governance, golden)
    activation["registryTransition"] = _registry_transition(sections, activation)
    return {
        "jurisdiction": "SG", "asOf": as_of.isoformat(), "activationReadiness": activation,
        "activePack": active, "valuesFromPack": values_pack, "valuesFromActivePack": bool(active),
        "packs": facts.get("packs") or [],
        "sections": sections,
        "certification": "Internal engineering configuration summary only — not a CPF Board, IRAS, MOM or PDPC "
                         "approval or certification.",
    }
