"""
engine/jurisdictions/singapore/statutory_summary.py
---------------------------------------------------
Super Admin Singapore statutory configuration summary (Phase 5.6) and the
Singapore report-template catalog. Pure: service.py gathers the facts
(packs, rows, evidence, PWM schedule statistics, templates) and this module
only arranges them into sections. No value here is a statutory rate — every
figure in the output is a persisted row value passed in by the caller; a
missing row is reported as NOT_CONFIGURED, never defaulted.

Report-template classification (ReportTemplate has no classification
column; this catalog is the single source for it, used by the summary API,
the seed script and the tests):
  EXPORT_READY        - a file/extract built to a published layout, which
                        the employer submits itself (IR8A AIS extract, CPF
                        EZPay FTP file). Not a submission, not an approval.
  SUBMISSION_SUPPORT  - figures the employer keys into / reconciles against
                        an official channel (SDL, CPF, SHG totals).
  INTERNAL_REPORT     - operational payroll report (register, summary, levy
                        reconciliation); no official format exists or is claimed.
  STATUTORY_WORKSPACE - internal compliance working view (PWM, LQS, IR21)
                        generated by a dedicated Singapore generator from
                        the existing evaluators (Phase 5.7); the generic
                        payslip-column generator refuses these types.
None of them is certified or approved by CPF Board, IRAS, MOM or PDPC
(`officialCertification` is False for every entry).
"""

from .labour import PWM_KEY_PREFIX, PWM_OT_RATE_PREFIX

CONFIGURED, PARTIAL, NOT_CONFIGURED = "CONFIGURED", "PARTIAL", "NOT_CONFIGURED"
# ReportTemplate.status lifecycle (models.py: Draft | Review | Approved | Published | Active | Superseded).
TEMPLATE_STATUSES = ("Draft", "Review", "Approved", "Published", "Active", "Superseded")
PASS, REVIEW, BLOCKED = "PASS", "REVIEW", "BLOCKED"

EXPORT_READY, SUBMISSION_SUPPORT = "EXPORT_READY", "SUBMISSION_SUPPORT"
INTERNAL_REPORT, STATUTORY_WORKSPACE = "INTERNAL_REPORT", "STATUTORY_WORKSPACE"
GENERIC_GENERATOR = "GENERIC_TEMPLATE"      # service.generate_report_from_template over real PayslipItem columns

WP_LEVY_PREFIX = "fwl_wp__"                 # engine/countries/singapore.work_permit_levy_key

_NOT_CERTIFIED = "Internal Zoiko report — not approved or certified by CPF Board, IRAS, MOM or PDPC."

# (templateKey, reportType, name, classification, generator, regulatoryAuthority, description)
SG_REPORT_TEMPLATES = (
    ("SG-IR8A", "SG_IR8A", "IR8A — Employment Income Data Extract (AIS)", EXPORT_READY,
     "POST /api/payroll/singapore/reports/ir8a", "IRAS",
     "EXPORT_READY extract of IR8A employment income per wage year for the employer's own AIS submission "
     "(AIS-API 2.0 or myTax Portal). Never reported as submitted to IRAS. " + _NOT_CERTIFIED),
    ("SG-SDL-MONTHLY", "SG_SDL_MONTHLY", "Skills Development Levy — Monthly Employer Total", SUBMISSION_SUPPORT,
     "POST /api/payroll/singapore/reports/sdl", "CPF Board (SDL collection)",
     "Monthly SDL payable (sum of per-employee SDL, rounded down) for the CPF submission. " + _NOT_CERTIFIED),
    ("SG-CPF-EZPAY", "SG_CPF_EZPAY", "CPF EZPay Contribution File (FTP specification)", EXPORT_READY,
     "POST /api/payroll/singapore/reports/cpf-ezpay", "CPF Board",
     "CPF EZPay (FTP) contribution file built to the published CPF Board specification; the employer uploads "
     "it through CPF EZPay (Corppass). " + _NOT_CERTIFIED),
    ("SG-PAYROLL-REGISTER", "SG_PAYROLL_REGISTER", "Singapore Payroll Register", INTERNAL_REPORT,
     GENERIC_GENERATOR, None,
     "INTERNAL_REPORT — one row per employee for a finalized payroll run: earnings, employee CPF, SHG, "
     "deductions, net pay and employer CPF / SDL / FWL, read from the run's persisted payslip columns. "
     + _NOT_CERTIFIED),
    ("SG-PAYROLL-SUMMARY", "SG_PAYROLL_SUMMARY", "Singapore Payroll Summary", INTERNAL_REPORT,
     GENERIC_GENERATOR, None,
     "INTERNAL_REPORT — run totals (gross pay, employee CPF, SHG, net pay, employer CPF, SDL, FWL) summed "
     "from the run's persisted payslip columns. " + _NOT_CERTIFIED),
    ("SG-CPF-CONTRIBUTION", "SG_CPF_CONTRIBUTION", "CPF Contribution Report", SUBMISSION_SUPPORT,
     GENERIC_GENERATOR, "CPF Board",
     "SUBMISSION_SUPPORT — employee and employer CPF per employee for a finalized run, for reconciliation "
     "against the CPF EZPay submission. Gross pay shown is total gross, not CPF-subject OW/AW (those are in "
     "each payslip's calculation trace). " + _NOT_CERTIFIED),
    ("SG-SHG-MONTHLY", "SG_SHG_MONTHLY", "Self-Help Group Contributions — Monthly", SUBMISSION_SUPPORT,
     GENERIC_GENERATOR, "CPF Board (SHG collection)",
     "SUBMISSION_SUPPORT — SHG deduction per employee for a finalized run, for reconciliation against the "
     "CPF submission (payment codes 02–05). The fund (CDAC/ECF/MBMF/SINDA) is on the employee record and in "
     "the payslip trace, not a report column. " + _NOT_CERTIFIED),
    ("SG-FWL-MONTHLY", "SG_FWL_MONTHLY", "Foreign Worker Levy — Monthly Reconciliation", INTERNAL_REPORT,
     GENERIC_GENERATOR, None,
     "INTERNAL_REPORT — employer levy cost per employee as computed by payroll, for reconciling against the "
     "MOM levy bill. MOM bills the levy; the employer files nothing from this report. " + _NOT_CERTIFIED),
    ("SG-PWM-COMPLIANCE", "SG_PWM_COMPLIANCE", "Progressive Wage Model Compliance Workspace", STATUTORY_WORKSPACE,
     "POST /api/payroll/singapore/reports/pwm-compliance", None,
     "STATUTORY_WORKSPACE — per wage month, each PWM-classified employee's floor and overtime gross "
     "requirement result (MET / SHORTFALL / NOT_EVALUATED) from the same PWM check the run preflight uses, "
     "with the sgp_pwm_overtime_schedules row and its MOM source. Not an MOM submission. " + _NOT_CERTIFIED),
    ("SG-IR21-REGISTER", "SG_IR21_REGISTER", "IR21 Tax Clearance Register", STATUTORY_WORKSPACE,
     "POST /api/payroll/singapore/reports/ir21-register", None,
     "STATUTORY_WORKSPACE — the year's IR21 cases and every case still holding pay, from the sgp_ir21_cases "
     "lifecycle: status, withholding, maker/checker, outstanding action and references. No IR21 tax is "
     "calculated. Not an IRAS filing. " + _NOT_CERTIFIED),
    ("SG-LQS-COMPLIANCE", "SG_LQS_COMPLIANCE", "Local Qualifying Salary Compliance Workspace", STATUTORY_WORKSPACE,
     "POST /api/payroll/singapore/reports/lqs-compliance", None,
     "STATUTORY_WORKSPACE — per wage month, each employee's LQS result as evaluated by the payroll engine "
     "(threshold, wages considered, basis, reference). The MOM foreign-worker quota computation is not "
     "performed. Not an MOM submission. " + _NOT_CERTIFIED),
)
SG_TEMPLATE_KEYS = tuple(t[0] for t in SG_REPORT_TEMPLATES)
# Report types the generic run-based generator must refuse: their subject is
# not a payslip column, so only their dedicated Singapore generator renders them.
SG_DEDICATED_GENERATOR_REPORT_TYPES = frozenset(t[1] for t in SG_REPORT_TEMPLATES if t[3] == STATUTORY_WORKSPACE)


def template_catalog_entry(template_key):
    for key, report_type, name, classification, generator, authority, description in SG_REPORT_TEMPLATES:
        if key == template_key:
            return {"templateKey": key, "reportType": report_type, "name": name, "classification": classification,
                    "generator": generator, "regulatoryAuthority": authority, "description": description,
                    "officialCertification": False}
    return None


def _value(rates, key):
    """A persisted ContributionRate as the caller serialized it, or None."""
    row = rates.get(key)
    if row is None:
        return None
    return {k: row.get(k) for k in ("label", "flatAmount", "employerRatePct", "textValue", "effectiveFrom",
                                    "effectiveTo", "sourceDocumentId")}


def _section(key, label, values, required, sources, notes=None, effective_date=None, status=None):
    present = [k for k in required if values.get(k) is not None]
    if status is None:
        status = CONFIGURED if len(present) == len(required) else (PARTIAL if present else NOT_CONFIGURED)
    return {"key": key, "label": label, "configured": status == CONFIGURED, "status": status,
            "effectiveDate": effective_date, "values": values,
            "missing": [k for k in required if values.get(k) is None],
            "sources": sources, "notes": notes or []}


def _sources_for(values, sources):
    ids = sorted({v["sourceDocumentId"] for v in values.values()
                  if isinstance(v, dict) and v.get("sourceDocumentId") is not None})
    return [sources.get(i, {"id": i, "missing": True}) for i in ids]


def _readiness_item(key, label, status, evidence):
    return {"key": key, "label": label, "status": status, "evidence": evidence}


def build_statutory_summary(facts: dict) -> dict:
    as_of = facts["as_of"]
    active, review = facts.get("active_pack"), facts.get("review_pack")
    values_pack = active or review
    rates, slabs, sources = facts.get("rates") or {}, facts.get("slabs") or {}, facts.get("sources") or {}
    effective = values_pack.get("effectiveFrom") if values_pack else None

    def val(key):
        return _value(rates, key)

    def count_prefix(prefix):
        return sum(1 for k in rates if k.startswith(prefix))

    sections = []

    cpf = {"owCeilingMonthly": val("cpf_ow_ceiling_monthly"), "annualWageCeiling": val("cpf_annual_wage_ceiling"),
           "ageBandSemantics": val("cpf_age_band_semantics"),
           "enforcementDayFollowingMonth": val("cpf_enforcement_day_following_month"),
           "rateBands": slabs.get("cpf_bands") or None, "cohorts": slabs.get("cpf_cohorts") or None}
    sections.append(_section(
        "cpf", "CPF", cpf, ("owCeilingMonthly", "annualWageCeiling", "rateBands"), _sources_for(cpf, sources),
        notes=["The AW ceiling is not a stored value: it is derived per employee as the annual wage ceiling less "
               "the total OW subject to CPF for the year (see the annualWageCeiling row label)."],
        effective_date=effective))

    sdl = {"rate": val("sdl"), "minimumMonthly": val("sdl_min_monthly"), "maximumMonthly": val("sdl_max_monthly")}
    sections.append(_section("sdl", "SDL", sdl, ("rate", "minimumMonthly", "maximumMonthly"),
                             _sources_for(sdl, sources), effective_date=effective))

    shg = {"fundBands": slabs.get("shg_bands") or None, "funds": slabs.get("shg_funds") or None,
           "fundCount": len(slabs.get("shg_funds") or []) or None}
    sections.append(_section("shg", "SHG", shg, ("fundBands", "funds"),
                             [sources[i] for i in slabs.get("shg_source_ids", []) if i in sources],
                             effective_date=effective))

    fwl = {"sPassMonthly": val("fwl_s_pass_monthly"), "workPermitLevyRows": count_prefix(WP_LEVY_PREFIX) or None,
           "paymentDueDay": val("fwl_payment_due_day"), "sPassEndDayBasis": val("fwl_s_pass_end_day_basis")}
    fwl_notes = []
    if fwl["sPassEndDayBasis"] is None:
        fwl_notes.append("fwl_s_pass_end_day_basis is not seeded (MOM does not state whether the end day is "
                         "levied) — a pass ending mid-month stays BLOCKED.")
    sections.append(_section("fwl", "FWL", fwl, ("sPassMonthly", "workPermitLevyRows"), _sources_for(fwl, sources),
                             notes=fwl_notes, effective_date=effective))

    lqs = {"fullTimeMonthly": val("lqs_full_time_monthly"), "partTimeHourly": val("lqs_part_time_hourly")}
    sections.append(_section("lqs", "LQS", lqs, ("fullTimeMonthly", "partTimeHourly"), _sources_for(lqs, sources),
                             effective_date=effective))

    pwm_table = facts.get("pwm_schedule") or {}
    pwm = {"floorRows": count_prefix(PWM_KEY_PREFIX) or None, "overtimeRateRows": count_prefix(PWM_OT_RATE_PREFIX) or None,
           "overtimeSchedule": pwm_table or None}
    sections.append(_section(
        "pwm", "PWM", pwm, ("floorRows", "overtimeSchedule"),
        [sources[i] for i in pwm_table.get("sourceDocumentIds", []) if i in sources],
        notes=["Overtime gross requirements are statutory reference data in sgp_pwm_overtime_schedules "
               "(tenant-independent, read-only); they are not pack rows and are not copied into payslips."],
        effective_date=effective))

    ais_calendar = facts.get("ais_calendar")
    iras = {"aisMandatoryEmployeeThreshold": val("ais_mandatory_employee_threshold"),
            "aisSubmissionMode": val("ais_submission_mode"), "aisFilingCalendar": ais_calendar,
            "retentionYearsFromYa": val("retention_iras_years_from_ya")}
    sections.append(_section(
        "iras", "IRAS (AIS / IR8A)", iras, ("aisMandatoryEmployeeThreshold", "aisSubmissionMode", "aisFilingCalendar"),
        _sources_for(iras, sources),
        notes=["IR8A is an EXPORT_READY extract; no AIS-API submission is built."], effective_date=effective))

    ir21 = {"departureTriggerMonths": val("ir21_departure_trigger_months"),
            "filingLeadMonths": val("ir21_filing_lead_months")}
    sections.append(_section("ir21", "IR21", ir21, ("departureTriggerMonths", "filingLeadMonths"),
                             _sources_for(ir21, sources),
                             notes=["IR21 cases are per organization (sgp_ir21_cases) and are not shown here."],
                             effective_date=effective))

    templates = {t["templateKey"]: t for t in facts.get("templates") or []}
    ezpay_template = templates.get("SG-CPF-EZPAY")
    ezpay = {"template": ({"status": ezpay_template["status"], "version": ezpay_template["version"]}
                          if ezpay_template else None),
             "enforcementDayFollowingMonth": val("cpf_enforcement_day_following_month")}
    sections.append(_section("ezpay", "CPF EZPay", ezpay, ("template",), _sources_for(ezpay, sources),
                             notes=["The employer uploads the file through CPF EZPay (Corppass); no direct CPF "
                                    "Board API is claimed."], effective_date=effective))

    # Draft values are never presented as in force: a section whose values
    # come from a non-Active pack keeps its completeness in
    # configurationStatus but is BLOCKED (Phase 5.7).
    for s in sections:
        s["configurationStatus"] = s["status"]
        s["inForce"] = bool(active) and s["status"] != NOT_CONFIGURED
        if not active and s["status"] in (CONFIGURED, PARTIAL):
            s["status"], s["configured"] = BLOCKED, False
            s["notes"] = s["notes"] + [
                f"Values are from {review['packId']} v{review['version']} ({review['status']}) — not in force until a "
                "Singapore pack is Active." if review else "No Singapore tax pack covers this date — not in force."]
        # Phase 5.8 — per-component lifecycle / validation / evidence state.
        # lifecycleState is the pack the values come from; validationState is
        # EXTERNAL_VALIDATION_REQUIRED until the §18 production gates are
        # evidenced (none is recorded in Zoiko), whatever the internal review.
        s["lifecycleState"] = ((values_pack["status"] or "").upper() if values_pack and s["configurationStatus"] != NOT_CONFIGURED
                               else NOT_CONFIGURED)
        s["validationState"] = "EXTERNAL_VALIDATION_REQUIRED"
        s["sourcesReviewed"] = f"{sum(1 for x in s['sources'] if x.get('reviewed'))}/{len(s['sources'])}"
        s["effectiveTo"] = values_pack.get("effectiveTo") if values_pack else None
        s["lastRetrievedAt"] = max((x["retrievedAt"] for x in s["sources"] if x.get("retrievedAt")), default=None)

    template_rows = []
    for key in SG_TEMPLATE_KEYS:
        entry = template_catalog_entry(key)
        row = templates.get(key)
        template_rows.append({
            **{k: entry[k] for k in ("templateKey", "reportType", "classification", "generator", "officialCertification")},
            "name": row["name"] if row else entry["name"],
            "present": row is not None,
            "id": row["id"] if row else None, "status": row["status"] if row else None,
            "version": row["version"] if row else None, "effectiveFrom": row["effectiveFrom"] if row else None,
            "documentScope": row["documentScope"] if row else None,
            # Lifecycle evidence (Phase 5.7): the approver is a column; the
            # approval / status-change times come from the audit trail.
            **{k: (row.get(k) if row else None) for k in (
                "approvedById", "approvedAt", "lastStatusChangeAt", "auditEntries", "versionCount",
                "previousVersionId", "sourceDocumentId", "sourceReferences", "regulatoryAuthority", "description",
                "updatedAt", "allowedNextStatuses")},
            "editable": (row["status"] in ("Draft", "Review", "Approved")) if row else None,
            "generatable": (row["status"] == "Active") if row else False,
        })
    unexpected = sorted(k for k in templates if k not in SG_TEMPLATE_KEYS)
    missing_templates = [r["templateKey"] for r in template_rows if not r["present"]]
    sections.append({
        "key": "reportTemplates", "label": "Reporting",
        "configured": not missing_templates,
        "status": CONFIGURED if not missing_templates else (PARTIAL if len(missing_templates) < len(template_rows)
                                                            else NOT_CONFIGURED),
        "effectiveDate": None,
        "values": {"expected": len(template_rows), "present": len(template_rows) - len(missing_templates),
                   "active": sum(1 for r in template_rows if r["status"] == "Active"),
                   # Every lifecycle state the ReportTemplate model defines; this repo has no
                   # "Deprecated" state — a retired version is Superseded.
                   "statusCounts": {st: sum(1 for r in template_rows if r["status"] == st) for st in TEMPLATE_STATUSES},
                   "generatorTypes": len({r["reportType"] for r in template_rows}),
                   "templates": template_rows, "unexpectedTemplateKeys": unexpected},
        "missing": missing_templates, "sources": [],
        "notes": ["Classification is Zoiko's own; no template is certified by CPF Board, IRAS, MOM or PDPC."],
    })

    unreviewed = [s for s in sources.values() if not s.get("reviewed")]
    golden = facts.get("latest_golden")
    items = [
        _readiness_item("active_pack", "Active Singapore tax pack on the date",
                        PASS if active else BLOCKED,
                        f"{active['packId']} v{active['version']}" if active else
                        ("No Active pack — values shown are from "
                         f"{review['packId']} v{review['version']} ({review['status']}), not in force"
                         if review else "No Singapore tax pack covers this date")),
        _readiness_item("statutory_sections", "Statutory sections configured",
                        PASS if all(s["configured"] for s in sections if s["key"] != "reportTemplates") else REVIEW,
                        ", ".join(f"{s['label']}: {s['status']}" for s in sections if s["key"] != "reportTemplates")),
        _readiness_item("source_evidence", "Source evidence reviewed",
                        PASS if sources and not unreviewed else REVIEW,
                        f"{len(sources) - len(unreviewed)} of {len(sources)} linked source artifacts reviewed"),
        _readiness_item("report_templates", "Singapore report templates present",
                        PASS if not missing_templates else REVIEW,
                        f"{len(template_rows) - len(missing_templates)} of {len(template_rows)} present"
                        + (f"; missing {', '.join(missing_templates)}" if missing_templates else "")),
        _readiness_item("golden_vectors", "Latest Singapore golden-vector certification run",
                        PASS if golden and golden.get("status") == "PASS" else REVIEW,
                        (f"{golden['status']} {golden['passedCases']}/{golden['totalCases']} at {golden['runAt']}"
                         if golden else "No run recorded")),
        _readiness_item("production_gates", "ZP-SG-ENG-001 §18 production gates G1–G8", BLOCKED,
                        "No gate evidence is recorded in Zoiko; external evidence is required."),
    ]
    overall = BLOCKED if any(i["status"] == BLOCKED for i in items) else (
        REVIEW if any(i["status"] == REVIEW for i in items) else PASS)
    sections.append({"key": "readiness", "label": "Readiness", "configured": overall == PASS, "status": overall,
                     "effectiveDate": None, "values": {"items": items}, "missing": [], "sources": [], "notes": []})

    pack_status = CONFIGURED if active else (BLOCKED if review else NOT_CONFIGURED)
    sections.insert(0, {
        "key": "pack", "label": "Statutory Pack", "configured": bool(active), "status": pack_status,
        "configurationStatus": CONFIGURED if values_pack else NOT_CONFIGURED, "inForce": bool(active),
        "effectiveDate": effective,
        "values": {"activePack": active, "valuesFromPack": values_pack, "valuesFromActivePack": bool(active),
                   "versions": facts.get("packs") or []},
        "missing": [] if active else ["activePack"], "sources": [],
        "notes": ([] if active else
                  [f"No Active Singapore pack on {as_of.isoformat()}"
                   + (f" — {review['packId']} v{review['version']} is {review['status']}; its values are shown for "
                      "review only and are not in force." if review else ".")]),
    })

    # Phase 5.8 — activation readiness (read-only; nothing is activated here).
    # Gates mirror service.set_jurisdiction_pack_status for SG tax packs.
    pack_source = sources.get(values_pack["sourceDocumentId"]) if values_pack and values_pack.get("sourceDocumentId") else None
    template_values = next(x for x in sections if x["key"] == "reportTemplates")["values"]
    pwm_values = next(x for x in sections if x["key"] == "pwm")["values"].get("overtimeSchedule") or {}
    activation = {
        "statutoryPack": {
            "status": values_pack["status"] if values_pack else None,
            "packId": values_pack["packId"] if values_pack else None,
            "version": values_pack["version"] if values_pack else None,
            "effectiveFrom": values_pack["effectiveFrom"] if values_pack else None,
            "source": ({k: pack_source.get(k) for k in ("id", "agency", "title", "url", "reviewed")} if pack_source else None),
            "sourceHash": pack_source.get("sha256") if pack_source else None,
            "approval": {"approvedById": values_pack.get("approvedById") if values_pack else None,
                         "distinctFromLastEditor": bool(values_pack and values_pack.get("approvedById")
                                                        and values_pack.get("approvedById") != values_pack.get("updatedById"))},
            "activation": "ACTIVE" if active else "NOT_ACTIVE",
            "activationGates": [
                {"key": "distinct_approver", "met": bool(values_pack and values_pack.get("approvedById")
                                                         and values_pack.get("approvedById") != values_pack.get("updatedById"))},
                {"key": "source_evidence_linked", "met": bool(values_pack and values_pack.get("sourceDocumentId"))},
                {"key": "effective_from_set", "met": bool(values_pack and values_pack.get("effectiveFrom"))},
                {"key": "latest_golden_run_pass", "met": bool(golden and golden.get("status") == "PASS")},
            ],
            "externalValidation": "EXTERNAL_VALIDATION_REQUIRED",
        },
        "reportTemplates": {"total": template_values["present"], **template_values["statusCounts"]},
        "pwm": {"rows": pwm_values.get("totalRows"), "schedules": pwm_values.get("schedules"),
                "sourceDocuments": len(pwm_values.get("sourceDocumentIds") or []),
                "latestRetrieved": pwm_values.get("latestRetrievedAt"), "lastSeeded": pwm_values.get("lastSeededAt")},
    }

    return {
        "jurisdiction": "SG", "asOf": as_of.isoformat(), "activationReadiness": activation,
        "activePack": active, "valuesFromPack": values_pack, "valuesFromActivePack": bool(active),
        "packs": facts.get("packs") or [],
        "sections": sections,
        "certification": "Internal engineering configuration summary only — not a CPF Board, IRAS, MOM or PDPC "
                         "approval or certification.",
    }
